services:
  tetherdns:
    image: tetherdns:latest
    container_name: tetherdns
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/tetherdns.db
      - SESSION_PASSWORD=tetherdns
      - SESSION_SECURE=false
      - NODE_ENV=production
      - TZ=Asia/Bangkok
    ports:
      - "3000:3000"