
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CloudflareTunnel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CloudflareTunnel
 * 
 */
export type CloudflareTunnelModel = runtime.Types.Result.DefaultSelection<Prisma.$CloudflareTunnelPayload>

export type AggregateCloudflareTunnel = {
  _count: CloudflareTunnelCountAggregateOutputType | null
  _avg: CloudflareTunnelAvgAggregateOutputType | null
  _sum: CloudflareTunnelSumAggregateOutputType | null
  _min: CloudflareTunnelMinAggregateOutputType | null
  _max: CloudflareTunnelMaxAggregateOutputType | null
}

export type CloudflareTunnelAvgAggregateOutputType = {
  id: number | null
  accountId: number | null
}

export type CloudflareTunnelSumAggregateOutputType = {
  id: number | null
  accountId: number | null
}

export type CloudflareTunnelMinAggregateOutputType = {
  id: number | null
  tunnelId: string | null
  name: string | null
  token: string | null
  status: string | null
  connections: string | null
  accountId: number | null
  createdAt: Date | null
}

export type CloudflareTunnelMaxAggregateOutputType = {
  id: number | null
  tunnelId: string | null
  name: string | null
  token: string | null
  status: string | null
  connections: string | null
  accountId: number | null
  createdAt: Date | null
}

export type CloudflareTunnelCountAggregateOutputType = {
  id: number
  tunnelId: number
  name: number
  token: number
  status: number
  connections: number
  accountId: number
  createdAt: number
  _all: number
}


export type CloudflareTunnelAvgAggregateInputType = {
  id?: true
  accountId?: true
}

export type CloudflareTunnelSumAggregateInputType = {
  id?: true
  accountId?: true
}

export type CloudflareTunnelMinAggregateInputType = {
  id?: true
  tunnelId?: true
  name?: true
  token?: true
  status?: true
  connections?: true
  accountId?: true
  createdAt?: true
}

export type CloudflareTunnelMaxAggregateInputType = {
  id?: true
  tunnelId?: true
  name?: true
  token?: true
  status?: true
  connections?: true
  accountId?: true
  createdAt?: true
}

export type CloudflareTunnelCountAggregateInputType = {
  id?: true
  tunnelId?: true
  name?: true
  token?: true
  status?: true
  connections?: true
  accountId?: true
  createdAt?: true
  _all?: true
}

export type CloudflareTunnelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CloudflareTunnel to aggregate.
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareTunnels to fetch.
   */
  orderBy?: Prisma.CloudflareTunnelOrderByWithRelationInput | Prisma.CloudflareTunnelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CloudflareTunnelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareTunnels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareTunnels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CloudflareTunnels
  **/
  _count?: true | CloudflareTunnelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CloudflareTunnelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CloudflareTunnelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CloudflareTunnelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CloudflareTunnelMaxAggregateInputType
}

export type GetCloudflareTunnelAggregateType<T extends CloudflareTunnelAggregateArgs> = {
      [P in keyof T & keyof AggregateCloudflareTunnel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCloudflareTunnel[P]>
    : Prisma.GetScalarType<T[P], AggregateCloudflareTunnel[P]>
}




export type CloudflareTunnelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CloudflareTunnelWhereInput
  orderBy?: Prisma.CloudflareTunnelOrderByWithAggregationInput | Prisma.CloudflareTunnelOrderByWithAggregationInput[]
  by: Prisma.CloudflareTunnelScalarFieldEnum[] | Prisma.CloudflareTunnelScalarFieldEnum
  having?: Prisma.CloudflareTunnelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CloudflareTunnelCountAggregateInputType | true
  _avg?: CloudflareTunnelAvgAggregateInputType
  _sum?: CloudflareTunnelSumAggregateInputType
  _min?: CloudflareTunnelMinAggregateInputType
  _max?: CloudflareTunnelMaxAggregateInputType
}

export type CloudflareTunnelGroupByOutputType = {
  id: number
  tunnelId: string
  name: string
  token: string
  status: string
  connections: string | null
  accountId: number
  createdAt: Date
  _count: CloudflareTunnelCountAggregateOutputType | null
  _avg: CloudflareTunnelAvgAggregateOutputType | null
  _sum: CloudflareTunnelSumAggregateOutputType | null
  _min: CloudflareTunnelMinAggregateOutputType | null
  _max: CloudflareTunnelMaxAggregateOutputType | null
}

export type GetCloudflareTunnelGroupByPayload<T extends CloudflareTunnelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CloudflareTunnelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CloudflareTunnelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CloudflareTunnelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CloudflareTunnelGroupByOutputType[P]>
      }
    >
  >



export type CloudflareTunnelWhereInput = {
  AND?: Prisma.CloudflareTunnelWhereInput | Prisma.CloudflareTunnelWhereInput[]
  OR?: Prisma.CloudflareTunnelWhereInput[]
  NOT?: Prisma.CloudflareTunnelWhereInput | Prisma.CloudflareTunnelWhereInput[]
  id?: Prisma.IntFilter<"CloudflareTunnel"> | number
  tunnelId?: Prisma.StringFilter<"CloudflareTunnel"> | string
  name?: Prisma.StringFilter<"CloudflareTunnel"> | string
  token?: Prisma.StringFilter<"CloudflareTunnel"> | string
  status?: Prisma.StringFilter<"CloudflareTunnel"> | string
  connections?: Prisma.StringNullableFilter<"CloudflareTunnel"> | string | null
  accountId?: Prisma.IntFilter<"CloudflareTunnel"> | number
  createdAt?: Prisma.DateTimeFilter<"CloudflareTunnel"> | Date | string
  account?: Prisma.XOR<Prisma.CloudflareAccountScalarRelationFilter, Prisma.CloudflareAccountWhereInput>
}

export type CloudflareTunnelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tunnelId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  status?: Prisma.SortOrder
  connections?: Prisma.SortOrderInput | Prisma.SortOrder
  accountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  account?: Prisma.CloudflareAccountOrderByWithRelationInput
}

export type CloudflareTunnelWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  tunnelId?: string
  AND?: Prisma.CloudflareTunnelWhereInput | Prisma.CloudflareTunnelWhereInput[]
  OR?: Prisma.CloudflareTunnelWhereInput[]
  NOT?: Prisma.CloudflareTunnelWhereInput | Prisma.CloudflareTunnelWhereInput[]
  name?: Prisma.StringFilter<"CloudflareTunnel"> | string
  token?: Prisma.StringFilter<"CloudflareTunnel"> | string
  status?: Prisma.StringFilter<"CloudflareTunnel"> | string
  connections?: Prisma.StringNullableFilter<"CloudflareTunnel"> | string | null
  accountId?: Prisma.IntFilter<"CloudflareTunnel"> | number
  createdAt?: Prisma.DateTimeFilter<"CloudflareTunnel"> | Date | string
  account?: Prisma.XOR<Prisma.CloudflareAccountScalarRelationFilter, Prisma.CloudflareAccountWhereInput>
}, "id" | "tunnelId">

export type CloudflareTunnelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tunnelId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  status?: Prisma.SortOrder
  connections?: Prisma.SortOrderInput | Prisma.SortOrder
  accountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CloudflareTunnelCountOrderByAggregateInput
  _avg?: Prisma.CloudflareTunnelAvgOrderByAggregateInput
  _max?: Prisma.CloudflareTunnelMaxOrderByAggregateInput
  _min?: Prisma.CloudflareTunnelMinOrderByAggregateInput
  _sum?: Prisma.CloudflareTunnelSumOrderByAggregateInput
}

export type CloudflareTunnelScalarWhereWithAggregatesInput = {
  AND?: Prisma.CloudflareTunnelScalarWhereWithAggregatesInput | Prisma.CloudflareTunnelScalarWhereWithAggregatesInput[]
  OR?: Prisma.CloudflareTunnelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CloudflareTunnelScalarWhereWithAggregatesInput | Prisma.CloudflareTunnelScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CloudflareTunnel"> | number
  tunnelId?: Prisma.StringWithAggregatesFilter<"CloudflareTunnel"> | string
  name?: Prisma.StringWithAggregatesFilter<"CloudflareTunnel"> | string
  token?: Prisma.StringWithAggregatesFilter<"CloudflareTunnel"> | string
  status?: Prisma.StringWithAggregatesFilter<"CloudflareTunnel"> | string
  connections?: Prisma.StringNullableWithAggregatesFilter<"CloudflareTunnel"> | string | null
  accountId?: Prisma.IntWithAggregatesFilter<"CloudflareTunnel"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CloudflareTunnel"> | Date | string
}

export type CloudflareTunnelCreateInput = {
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  createdAt?: Date | string
  account: Prisma.CloudflareAccountCreateNestedOneWithoutTunnelsInput
}

export type CloudflareTunnelUncheckedCreateInput = {
  id?: number
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  accountId: number
  createdAt?: Date | string
}

export type CloudflareTunnelUpdateInput = {
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  account?: Prisma.CloudflareAccountUpdateOneRequiredWithoutTunnelsNestedInput
}

export type CloudflareTunnelUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareTunnelCreateManyInput = {
  id?: number
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  accountId: number
  createdAt?: Date | string
}

export type CloudflareTunnelUpdateManyMutationInput = {
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareTunnelUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accountId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareTunnelListRelationFilter = {
  every?: Prisma.CloudflareTunnelWhereInput
  some?: Prisma.CloudflareTunnelWhereInput
  none?: Prisma.CloudflareTunnelWhereInput
}

export type CloudflareTunnelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CloudflareTunnelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tunnelId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  status?: Prisma.SortOrder
  connections?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareTunnelAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
}

export type CloudflareTunnelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tunnelId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  status?: Prisma.SortOrder
  connections?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareTunnelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tunnelId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  token?: Prisma.SortOrder
  status?: Prisma.SortOrder
  connections?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareTunnelSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accountId?: Prisma.SortOrder
}

export type CloudflareTunnelCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput> | Prisma.CloudflareTunnelCreateWithoutAccountInput[] | Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput | Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.CloudflareTunnelCreateManyAccountInputEnvelope
  connect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
}

export type CloudflareTunnelUncheckedCreateNestedManyWithoutAccountInput = {
  create?: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput> | Prisma.CloudflareTunnelCreateWithoutAccountInput[] | Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput | Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput[]
  createMany?: Prisma.CloudflareTunnelCreateManyAccountInputEnvelope
  connect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
}

export type CloudflareTunnelUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput> | Prisma.CloudflareTunnelCreateWithoutAccountInput[] | Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput | Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.CloudflareTunnelUpsertWithWhereUniqueWithoutAccountInput | Prisma.CloudflareTunnelUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.CloudflareTunnelCreateManyAccountInputEnvelope
  set?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  disconnect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  delete?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  connect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  update?: Prisma.CloudflareTunnelUpdateWithWhereUniqueWithoutAccountInput | Prisma.CloudflareTunnelUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.CloudflareTunnelUpdateManyWithWhereWithoutAccountInput | Prisma.CloudflareTunnelUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.CloudflareTunnelScalarWhereInput | Prisma.CloudflareTunnelScalarWhereInput[]
}

export type CloudflareTunnelUncheckedUpdateManyWithoutAccountNestedInput = {
  create?: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput> | Prisma.CloudflareTunnelCreateWithoutAccountInput[] | Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput[]
  connectOrCreate?: Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput | Prisma.CloudflareTunnelCreateOrConnectWithoutAccountInput[]
  upsert?: Prisma.CloudflareTunnelUpsertWithWhereUniqueWithoutAccountInput | Prisma.CloudflareTunnelUpsertWithWhereUniqueWithoutAccountInput[]
  createMany?: Prisma.CloudflareTunnelCreateManyAccountInputEnvelope
  set?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  disconnect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  delete?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  connect?: Prisma.CloudflareTunnelWhereUniqueInput | Prisma.CloudflareTunnelWhereUniqueInput[]
  update?: Prisma.CloudflareTunnelUpdateWithWhereUniqueWithoutAccountInput | Prisma.CloudflareTunnelUpdateWithWhereUniqueWithoutAccountInput[]
  updateMany?: Prisma.CloudflareTunnelUpdateManyWithWhereWithoutAccountInput | Prisma.CloudflareTunnelUpdateManyWithWhereWithoutAccountInput[]
  deleteMany?: Prisma.CloudflareTunnelScalarWhereInput | Prisma.CloudflareTunnelScalarWhereInput[]
}

export type CloudflareTunnelCreateWithoutAccountInput = {
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  createdAt?: Date | string
}

export type CloudflareTunnelUncheckedCreateWithoutAccountInput = {
  id?: number
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  createdAt?: Date | string
}

export type CloudflareTunnelCreateOrConnectWithoutAccountInput = {
  where: Prisma.CloudflareTunnelWhereUniqueInput
  create: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput>
}

export type CloudflareTunnelCreateManyAccountInputEnvelope = {
  data: Prisma.CloudflareTunnelCreateManyAccountInput | Prisma.CloudflareTunnelCreateManyAccountInput[]
}

export type CloudflareTunnelUpsertWithWhereUniqueWithoutAccountInput = {
  where: Prisma.CloudflareTunnelWhereUniqueInput
  update: Prisma.XOR<Prisma.CloudflareTunnelUpdateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedUpdateWithoutAccountInput>
  create: Prisma.XOR<Prisma.CloudflareTunnelCreateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedCreateWithoutAccountInput>
}

export type CloudflareTunnelUpdateWithWhereUniqueWithoutAccountInput = {
  where: Prisma.CloudflareTunnelWhereUniqueInput
  data: Prisma.XOR<Prisma.CloudflareTunnelUpdateWithoutAccountInput, Prisma.CloudflareTunnelUncheckedUpdateWithoutAccountInput>
}

export type CloudflareTunnelUpdateManyWithWhereWithoutAccountInput = {
  where: Prisma.CloudflareTunnelScalarWhereInput
  data: Prisma.XOR<Prisma.CloudflareTunnelUpdateManyMutationInput, Prisma.CloudflareTunnelUncheckedUpdateManyWithoutAccountInput>
}

export type CloudflareTunnelScalarWhereInput = {
  AND?: Prisma.CloudflareTunnelScalarWhereInput | Prisma.CloudflareTunnelScalarWhereInput[]
  OR?: Prisma.CloudflareTunnelScalarWhereInput[]
  NOT?: Prisma.CloudflareTunnelScalarWhereInput | Prisma.CloudflareTunnelScalarWhereInput[]
  id?: Prisma.IntFilter<"CloudflareTunnel"> | number
  tunnelId?: Prisma.StringFilter<"CloudflareTunnel"> | string
  name?: Prisma.StringFilter<"CloudflareTunnel"> | string
  token?: Prisma.StringFilter<"CloudflareTunnel"> | string
  status?: Prisma.StringFilter<"CloudflareTunnel"> | string
  connections?: Prisma.StringNullableFilter<"CloudflareTunnel"> | string | null
  accountId?: Prisma.IntFilter<"CloudflareTunnel"> | number
  createdAt?: Prisma.DateTimeFilter<"CloudflareTunnel"> | Date | string
}

export type CloudflareTunnelCreateManyAccountInput = {
  id?: number
  tunnelId: string
  name: string
  token: string
  status?: string
  connections?: string | null
  createdAt?: Date | string
}

export type CloudflareTunnelUpdateWithoutAccountInput = {
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareTunnelUncheckedUpdateWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareTunnelUncheckedUpdateManyWithoutAccountInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tunnelId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  connections?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CloudflareTunnelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tunnelId?: boolean
  name?: boolean
  token?: boolean
  status?: boolean
  connections?: boolean
  accountId?: boolean
  createdAt?: boolean
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cloudflareTunnel"]>

export type CloudflareTunnelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tunnelId?: boolean
  name?: boolean
  token?: boolean
  status?: boolean
  connections?: boolean
  accountId?: boolean
  createdAt?: boolean
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cloudflareTunnel"]>

export type CloudflareTunnelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tunnelId?: boolean
  name?: boolean
  token?: boolean
  status?: boolean
  connections?: boolean
  accountId?: boolean
  createdAt?: boolean
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cloudflareTunnel"]>

export type CloudflareTunnelSelectScalar = {
  id?: boolean
  tunnelId?: boolean
  name?: boolean
  token?: boolean
  status?: boolean
  connections?: boolean
  accountId?: boolean
  createdAt?: boolean
}

export type CloudflareTunnelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tunnelId" | "name" | "token" | "status" | "connections" | "accountId" | "createdAt", ExtArgs["result"]["cloudflareTunnel"]>
export type CloudflareTunnelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}
export type CloudflareTunnelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}
export type CloudflareTunnelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  account?: boolean | Prisma.CloudflareAccountDefaultArgs<ExtArgs>
}

export type $CloudflareTunnelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CloudflareTunnel"
  objects: {
    account: Prisma.$CloudflareAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    tunnelId: string
    name: string
    token: string
    status: string
    connections: string | null
    accountId: number
    createdAt: Date
  }, ExtArgs["result"]["cloudflareTunnel"]>
  composites: {}
}

export type CloudflareTunnelGetPayload<S extends boolean | null | undefined | CloudflareTunnelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload, S>

export type CloudflareTunnelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CloudflareTunnelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CloudflareTunnelCountAggregateInputType | true
  }

export interface CloudflareTunnelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CloudflareTunnel'], meta: { name: 'CloudflareTunnel' } }
  /**
   * Find zero or one CloudflareTunnel that matches the filter.
   * @param {CloudflareTunnelFindUniqueArgs} args - Arguments to find a CloudflareTunnel
   * @example
   * // Get one CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CloudflareTunnelFindUniqueArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CloudflareTunnel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CloudflareTunnelFindUniqueOrThrowArgs} args - Arguments to find a CloudflareTunnel
   * @example
   * // Get one CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CloudflareTunnelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CloudflareTunnel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelFindFirstArgs} args - Arguments to find a CloudflareTunnel
   * @example
   * // Get one CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CloudflareTunnelFindFirstArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelFindFirstArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CloudflareTunnel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelFindFirstOrThrowArgs} args - Arguments to find a CloudflareTunnel
   * @example
   * // Get one CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CloudflareTunnelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CloudflareTunnels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CloudflareTunnels
   * const cloudflareTunnels = await prisma.cloudflareTunnel.findMany()
   * 
   * // Get first 10 CloudflareTunnels
   * const cloudflareTunnels = await prisma.cloudflareTunnel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cloudflareTunnelWithIdOnly = await prisma.cloudflareTunnel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CloudflareTunnelFindManyArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CloudflareTunnel.
   * @param {CloudflareTunnelCreateArgs} args - Arguments to create a CloudflareTunnel.
   * @example
   * // Create one CloudflareTunnel
   * const CloudflareTunnel = await prisma.cloudflareTunnel.create({
   *   data: {
   *     // ... data to create a CloudflareTunnel
   *   }
   * })
   * 
   */
  create<T extends CloudflareTunnelCreateArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelCreateArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CloudflareTunnels.
   * @param {CloudflareTunnelCreateManyArgs} args - Arguments to create many CloudflareTunnels.
   * @example
   * // Create many CloudflareTunnels
   * const cloudflareTunnel = await prisma.cloudflareTunnel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CloudflareTunnelCreateManyArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CloudflareTunnels and returns the data saved in the database.
   * @param {CloudflareTunnelCreateManyAndReturnArgs} args - Arguments to create many CloudflareTunnels.
   * @example
   * // Create many CloudflareTunnels
   * const cloudflareTunnel = await prisma.cloudflareTunnel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CloudflareTunnels and only return the `id`
   * const cloudflareTunnelWithIdOnly = await prisma.cloudflareTunnel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CloudflareTunnelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CloudflareTunnel.
   * @param {CloudflareTunnelDeleteArgs} args - Arguments to delete one CloudflareTunnel.
   * @example
   * // Delete one CloudflareTunnel
   * const CloudflareTunnel = await prisma.cloudflareTunnel.delete({
   *   where: {
   *     // ... filter to delete one CloudflareTunnel
   *   }
   * })
   * 
   */
  delete<T extends CloudflareTunnelDeleteArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelDeleteArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CloudflareTunnel.
   * @param {CloudflareTunnelUpdateArgs} args - Arguments to update one CloudflareTunnel.
   * @example
   * // Update one CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CloudflareTunnelUpdateArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelUpdateArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CloudflareTunnels.
   * @param {CloudflareTunnelDeleteManyArgs} args - Arguments to filter CloudflareTunnels to delete.
   * @example
   * // Delete a few CloudflareTunnels
   * const { count } = await prisma.cloudflareTunnel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CloudflareTunnelDeleteManyArgs>(args?: Prisma.SelectSubset<T, CloudflareTunnelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CloudflareTunnels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CloudflareTunnels
   * const cloudflareTunnel = await prisma.cloudflareTunnel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CloudflareTunnelUpdateManyArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CloudflareTunnels and returns the data updated in the database.
   * @param {CloudflareTunnelUpdateManyAndReturnArgs} args - Arguments to update many CloudflareTunnels.
   * @example
   * // Update many CloudflareTunnels
   * const cloudflareTunnel = await prisma.cloudflareTunnel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CloudflareTunnels and only return the `id`
   * const cloudflareTunnelWithIdOnly = await prisma.cloudflareTunnel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CloudflareTunnelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CloudflareTunnel.
   * @param {CloudflareTunnelUpsertArgs} args - Arguments to update or create a CloudflareTunnel.
   * @example
   * // Update or create a CloudflareTunnel
   * const cloudflareTunnel = await prisma.cloudflareTunnel.upsert({
   *   create: {
   *     // ... data to create a CloudflareTunnel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CloudflareTunnel we want to update
   *   }
   * })
   */
  upsert<T extends CloudflareTunnelUpsertArgs>(args: Prisma.SelectSubset<T, CloudflareTunnelUpsertArgs<ExtArgs>>): Prisma.Prisma__CloudflareTunnelClient<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CloudflareTunnels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelCountArgs} args - Arguments to filter CloudflareTunnels to count.
   * @example
   * // Count the number of CloudflareTunnels
   * const count = await prisma.cloudflareTunnel.count({
   *   where: {
   *     // ... the filter for the CloudflareTunnels we want to count
   *   }
   * })
  **/
  count<T extends CloudflareTunnelCountArgs>(
    args?: Prisma.Subset<T, CloudflareTunnelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CloudflareTunnelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CloudflareTunnel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CloudflareTunnelAggregateArgs>(args: Prisma.Subset<T, CloudflareTunnelAggregateArgs>): Prisma.PrismaPromise<GetCloudflareTunnelAggregateType<T>>

  /**
   * Group by CloudflareTunnel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareTunnelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CloudflareTunnelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CloudflareTunnelGroupByArgs['orderBy'] }
      : { orderBy?: CloudflareTunnelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CloudflareTunnelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCloudflareTunnelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CloudflareTunnel model
 */
readonly fields: CloudflareTunnelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CloudflareTunnel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CloudflareTunnelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  account<T extends Prisma.CloudflareAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CloudflareAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CloudflareTunnel model
 */
export interface CloudflareTunnelFieldRefs {
  readonly id: Prisma.FieldRef<"CloudflareTunnel", 'Int'>
  readonly tunnelId: Prisma.FieldRef<"CloudflareTunnel", 'String'>
  readonly name: Prisma.FieldRef<"CloudflareTunnel", 'String'>
  readonly token: Prisma.FieldRef<"CloudflareTunnel", 'String'>
  readonly status: Prisma.FieldRef<"CloudflareTunnel", 'String'>
  readonly connections: Prisma.FieldRef<"CloudflareTunnel", 'String'>
  readonly accountId: Prisma.FieldRef<"CloudflareTunnel", 'Int'>
  readonly createdAt: Prisma.FieldRef<"CloudflareTunnel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CloudflareTunnel findUnique
 */
export type CloudflareTunnelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareTunnel to fetch.
   */
  where: Prisma.CloudflareTunnelWhereUniqueInput
}

/**
 * CloudflareTunnel findUniqueOrThrow
 */
export type CloudflareTunnelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareTunnel to fetch.
   */
  where: Prisma.CloudflareTunnelWhereUniqueInput
}

/**
 * CloudflareTunnel findFirst
 */
export type CloudflareTunnelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareTunnel to fetch.
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareTunnels to fetch.
   */
  orderBy?: Prisma.CloudflareTunnelOrderByWithRelationInput | Prisma.CloudflareTunnelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CloudflareTunnels.
   */
  cursor?: Prisma.CloudflareTunnelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareTunnels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareTunnels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareTunnels.
   */
  distinct?: Prisma.CloudflareTunnelScalarFieldEnum | Prisma.CloudflareTunnelScalarFieldEnum[]
}

/**
 * CloudflareTunnel findFirstOrThrow
 */
export type CloudflareTunnelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareTunnel to fetch.
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareTunnels to fetch.
   */
  orderBy?: Prisma.CloudflareTunnelOrderByWithRelationInput | Prisma.CloudflareTunnelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CloudflareTunnels.
   */
  cursor?: Prisma.CloudflareTunnelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareTunnels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareTunnels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareTunnels.
   */
  distinct?: Prisma.CloudflareTunnelScalarFieldEnum | Prisma.CloudflareTunnelScalarFieldEnum[]
}

/**
 * CloudflareTunnel findMany
 */
export type CloudflareTunnelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareTunnels to fetch.
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareTunnels to fetch.
   */
  orderBy?: Prisma.CloudflareTunnelOrderByWithRelationInput | Prisma.CloudflareTunnelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CloudflareTunnels.
   */
  cursor?: Prisma.CloudflareTunnelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareTunnels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareTunnels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareTunnels.
   */
  distinct?: Prisma.CloudflareTunnelScalarFieldEnum | Prisma.CloudflareTunnelScalarFieldEnum[]
}

/**
 * CloudflareTunnel create
 */
export type CloudflareTunnelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * The data needed to create a CloudflareTunnel.
   */
  data: Prisma.XOR<Prisma.CloudflareTunnelCreateInput, Prisma.CloudflareTunnelUncheckedCreateInput>
}

/**
 * CloudflareTunnel createMany
 */
export type CloudflareTunnelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CloudflareTunnels.
   */
  data: Prisma.CloudflareTunnelCreateManyInput | Prisma.CloudflareTunnelCreateManyInput[]
}

/**
 * CloudflareTunnel createManyAndReturn
 */
export type CloudflareTunnelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * The data used to create many CloudflareTunnels.
   */
  data: Prisma.CloudflareTunnelCreateManyInput | Prisma.CloudflareTunnelCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CloudflareTunnel update
 */
export type CloudflareTunnelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * The data needed to update a CloudflareTunnel.
   */
  data: Prisma.XOR<Prisma.CloudflareTunnelUpdateInput, Prisma.CloudflareTunnelUncheckedUpdateInput>
  /**
   * Choose, which CloudflareTunnel to update.
   */
  where: Prisma.CloudflareTunnelWhereUniqueInput
}

/**
 * CloudflareTunnel updateMany
 */
export type CloudflareTunnelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CloudflareTunnels.
   */
  data: Prisma.XOR<Prisma.CloudflareTunnelUpdateManyMutationInput, Prisma.CloudflareTunnelUncheckedUpdateManyInput>
  /**
   * Filter which CloudflareTunnels to update
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * Limit how many CloudflareTunnels to update.
   */
  limit?: number
}

/**
 * CloudflareTunnel updateManyAndReturn
 */
export type CloudflareTunnelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * The data used to update CloudflareTunnels.
   */
  data: Prisma.XOR<Prisma.CloudflareTunnelUpdateManyMutationInput, Prisma.CloudflareTunnelUncheckedUpdateManyInput>
  /**
   * Filter which CloudflareTunnels to update
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * Limit how many CloudflareTunnels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CloudflareTunnel upsert
 */
export type CloudflareTunnelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * The filter to search for the CloudflareTunnel to update in case it exists.
   */
  where: Prisma.CloudflareTunnelWhereUniqueInput
  /**
   * In case the CloudflareTunnel found by the `where` argument doesn't exist, create a new CloudflareTunnel with this data.
   */
  create: Prisma.XOR<Prisma.CloudflareTunnelCreateInput, Prisma.CloudflareTunnelUncheckedCreateInput>
  /**
   * In case the CloudflareTunnel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CloudflareTunnelUpdateInput, Prisma.CloudflareTunnelUncheckedUpdateInput>
}

/**
 * CloudflareTunnel delete
 */
export type CloudflareTunnelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  /**
   * Filter which CloudflareTunnel to delete.
   */
  where: Prisma.CloudflareTunnelWhereUniqueInput
}

/**
 * CloudflareTunnel deleteMany
 */
export type CloudflareTunnelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CloudflareTunnels to delete
   */
  where?: Prisma.CloudflareTunnelWhereInput
  /**
   * Limit how many CloudflareTunnels to delete.
   */
  limit?: number
}

/**
 * CloudflareTunnel without action
 */
export type CloudflareTunnelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
}
