
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CloudflareAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CloudflareAccount
 * 
 */
export type CloudflareAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$CloudflareAccountPayload>

export type AggregateCloudflareAccount = {
  _count: CloudflareAccountCountAggregateOutputType | null
  _avg: CloudflareAccountAvgAggregateOutputType | null
  _sum: CloudflareAccountSumAggregateOutputType | null
  _min: CloudflareAccountMinAggregateOutputType | null
  _max: CloudflareAccountMaxAggregateOutputType | null
}

export type CloudflareAccountAvgAggregateOutputType = {
  id: number | null
}

export type CloudflareAccountSumAggregateOutputType = {
  id: number | null
}

export type CloudflareAccountMinAggregateOutputType = {
  id: number | null
  providerType: string | null
  label: string | null
  email: string | null
  apiToken: string | null
  createdAt: Date | null
}

export type CloudflareAccountMaxAggregateOutputType = {
  id: number | null
  providerType: string | null
  label: string | null
  email: string | null
  apiToken: string | null
  createdAt: Date | null
}

export type CloudflareAccountCountAggregateOutputType = {
  id: number
  providerType: number
  label: number
  email: number
  apiToken: number
  createdAt: number
  _all: number
}


export type CloudflareAccountAvgAggregateInputType = {
  id?: true
}

export type CloudflareAccountSumAggregateInputType = {
  id?: true
}

export type CloudflareAccountMinAggregateInputType = {
  id?: true
  providerType?: true
  label?: true
  email?: true
  apiToken?: true
  createdAt?: true
}

export type CloudflareAccountMaxAggregateInputType = {
  id?: true
  providerType?: true
  label?: true
  email?: true
  apiToken?: true
  createdAt?: true
}

export type CloudflareAccountCountAggregateInputType = {
  id?: true
  providerType?: true
  label?: true
  email?: true
  apiToken?: true
  createdAt?: true
  _all?: true
}

export type CloudflareAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CloudflareAccount to aggregate.
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareAccounts to fetch.
   */
  orderBy?: Prisma.CloudflareAccountOrderByWithRelationInput | Prisma.CloudflareAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CloudflareAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CloudflareAccounts
  **/
  _count?: true | CloudflareAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CloudflareAccountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CloudflareAccountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CloudflareAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CloudflareAccountMaxAggregateInputType
}

export type GetCloudflareAccountAggregateType<T extends CloudflareAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateCloudflareAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCloudflareAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateCloudflareAccount[P]>
}




export type CloudflareAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CloudflareAccountWhereInput
  orderBy?: Prisma.CloudflareAccountOrderByWithAggregationInput | Prisma.CloudflareAccountOrderByWithAggregationInput[]
  by: Prisma.CloudflareAccountScalarFieldEnum[] | Prisma.CloudflareAccountScalarFieldEnum
  having?: Prisma.CloudflareAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CloudflareAccountCountAggregateInputType | true
  _avg?: CloudflareAccountAvgAggregateInputType
  _sum?: CloudflareAccountSumAggregateInputType
  _min?: CloudflareAccountMinAggregateInputType
  _max?: CloudflareAccountMaxAggregateInputType
}

export type CloudflareAccountGroupByOutputType = {
  id: number
  providerType: string
  label: string
  email: string | null
  apiToken: string
  createdAt: Date
  _count: CloudflareAccountCountAggregateOutputType | null
  _avg: CloudflareAccountAvgAggregateOutputType | null
  _sum: CloudflareAccountSumAggregateOutputType | null
  _min: CloudflareAccountMinAggregateOutputType | null
  _max: CloudflareAccountMaxAggregateOutputType | null
}

export type GetCloudflareAccountGroupByPayload<T extends CloudflareAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CloudflareAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CloudflareAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CloudflareAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CloudflareAccountGroupByOutputType[P]>
      }
    >
  >



export type CloudflareAccountWhereInput = {
  AND?: Prisma.CloudflareAccountWhereInput | Prisma.CloudflareAccountWhereInput[]
  OR?: Prisma.CloudflareAccountWhereInput[]
  NOT?: Prisma.CloudflareAccountWhereInput | Prisma.CloudflareAccountWhereInput[]
  id?: Prisma.IntFilter<"CloudflareAccount"> | number
  providerType?: Prisma.StringFilter<"CloudflareAccount"> | string
  label?: Prisma.StringFilter<"CloudflareAccount"> | string
  email?: Prisma.StringNullableFilter<"CloudflareAccount"> | string | null
  apiToken?: Prisma.StringFilter<"CloudflareAccount"> | string
  createdAt?: Prisma.DateTimeFilter<"CloudflareAccount"> | Date | string
  zones?: Prisma.ZoneListRelationFilter
  tunnels?: Prisma.CloudflareTunnelListRelationFilter
}

export type CloudflareAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  providerType?: Prisma.SortOrder
  label?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  apiToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  zones?: Prisma.ZoneOrderByRelationAggregateInput
  tunnels?: Prisma.CloudflareTunnelOrderByRelationAggregateInput
}

export type CloudflareAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.CloudflareAccountWhereInput | Prisma.CloudflareAccountWhereInput[]
  OR?: Prisma.CloudflareAccountWhereInput[]
  NOT?: Prisma.CloudflareAccountWhereInput | Prisma.CloudflareAccountWhereInput[]
  providerType?: Prisma.StringFilter<"CloudflareAccount"> | string
  label?: Prisma.StringFilter<"CloudflareAccount"> | string
  email?: Prisma.StringNullableFilter<"CloudflareAccount"> | string | null
  apiToken?: Prisma.StringFilter<"CloudflareAccount"> | string
  createdAt?: Prisma.DateTimeFilter<"CloudflareAccount"> | Date | string
  zones?: Prisma.ZoneListRelationFilter
  tunnels?: Prisma.CloudflareTunnelListRelationFilter
}, "id">

export type CloudflareAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  providerType?: Prisma.SortOrder
  label?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  apiToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CloudflareAccountCountOrderByAggregateInput
  _avg?: Prisma.CloudflareAccountAvgOrderByAggregateInput
  _max?: Prisma.CloudflareAccountMaxOrderByAggregateInput
  _min?: Prisma.CloudflareAccountMinOrderByAggregateInput
  _sum?: Prisma.CloudflareAccountSumOrderByAggregateInput
}

export type CloudflareAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.CloudflareAccountScalarWhereWithAggregatesInput | Prisma.CloudflareAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.CloudflareAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CloudflareAccountScalarWhereWithAggregatesInput | Prisma.CloudflareAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"CloudflareAccount"> | number
  providerType?: Prisma.StringWithAggregatesFilter<"CloudflareAccount"> | string
  label?: Prisma.StringWithAggregatesFilter<"CloudflareAccount"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"CloudflareAccount"> | string | null
  apiToken?: Prisma.StringWithAggregatesFilter<"CloudflareAccount"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CloudflareAccount"> | Date | string
}

export type CloudflareAccountCreateInput = {
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  zones?: Prisma.ZoneCreateNestedManyWithoutAccountInput
  tunnels?: Prisma.CloudflareTunnelCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountUncheckedCreateInput = {
  id?: number
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  zones?: Prisma.ZoneUncheckedCreateNestedManyWithoutAccountInput
  tunnels?: Prisma.CloudflareTunnelUncheckedCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountUpdateInput = {
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  zones?: Prisma.ZoneUpdateManyWithoutAccountNestedInput
  tunnels?: Prisma.CloudflareTunnelUpdateManyWithoutAccountNestedInput
}

export type CloudflareAccountUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  zones?: Prisma.ZoneUncheckedUpdateManyWithoutAccountNestedInput
  tunnels?: Prisma.CloudflareTunnelUncheckedUpdateManyWithoutAccountNestedInput
}

export type CloudflareAccountCreateManyInput = {
  id?: number
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
}

export type CloudflareAccountUpdateManyMutationInput = {
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareAccountUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CloudflareAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  providerType?: Prisma.SortOrder
  label?: Prisma.SortOrder
  email?: Prisma.SortOrder
  apiToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareAccountAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CloudflareAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  providerType?: Prisma.SortOrder
  label?: Prisma.SortOrder
  email?: Prisma.SortOrder
  apiToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  providerType?: Prisma.SortOrder
  label?: Prisma.SortOrder
  email?: Prisma.SortOrder
  apiToken?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CloudflareAccountSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CloudflareAccountNullableScalarRelationFilter = {
  is?: Prisma.CloudflareAccountWhereInput | null
  isNot?: Prisma.CloudflareAccountWhereInput | null
}

export type CloudflareAccountScalarRelationFilter = {
  is?: Prisma.CloudflareAccountWhereInput
  isNot?: Prisma.CloudflareAccountWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CloudflareAccountCreateNestedOneWithoutZonesInput = {
  create?: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutZonesInput, Prisma.CloudflareAccountUncheckedCreateWithoutZonesInput>
  connectOrCreate?: Prisma.CloudflareAccountCreateOrConnectWithoutZonesInput
  connect?: Prisma.CloudflareAccountWhereUniqueInput
}

export type CloudflareAccountUpdateOneWithoutZonesNestedInput = {
  create?: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutZonesInput, Prisma.CloudflareAccountUncheckedCreateWithoutZonesInput>
  connectOrCreate?: Prisma.CloudflareAccountCreateOrConnectWithoutZonesInput
  upsert?: Prisma.CloudflareAccountUpsertWithoutZonesInput
  disconnect?: Prisma.CloudflareAccountWhereInput | boolean
  delete?: Prisma.CloudflareAccountWhereInput | boolean
  connect?: Prisma.CloudflareAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CloudflareAccountUpdateToOneWithWhereWithoutZonesInput, Prisma.CloudflareAccountUpdateWithoutZonesInput>, Prisma.CloudflareAccountUncheckedUpdateWithoutZonesInput>
}

export type CloudflareAccountCreateNestedOneWithoutTunnelsInput = {
  create?: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedCreateWithoutTunnelsInput>
  connectOrCreate?: Prisma.CloudflareAccountCreateOrConnectWithoutTunnelsInput
  connect?: Prisma.CloudflareAccountWhereUniqueInput
}

export type CloudflareAccountUpdateOneRequiredWithoutTunnelsNestedInput = {
  create?: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedCreateWithoutTunnelsInput>
  connectOrCreate?: Prisma.CloudflareAccountCreateOrConnectWithoutTunnelsInput
  upsert?: Prisma.CloudflareAccountUpsertWithoutTunnelsInput
  connect?: Prisma.CloudflareAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CloudflareAccountUpdateToOneWithWhereWithoutTunnelsInput, Prisma.CloudflareAccountUpdateWithoutTunnelsInput>, Prisma.CloudflareAccountUncheckedUpdateWithoutTunnelsInput>
}

export type CloudflareAccountCreateWithoutZonesInput = {
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  tunnels?: Prisma.CloudflareTunnelCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountUncheckedCreateWithoutZonesInput = {
  id?: number
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  tunnels?: Prisma.CloudflareTunnelUncheckedCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountCreateOrConnectWithoutZonesInput = {
  where: Prisma.CloudflareAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutZonesInput, Prisma.CloudflareAccountUncheckedCreateWithoutZonesInput>
}

export type CloudflareAccountUpsertWithoutZonesInput = {
  update: Prisma.XOR<Prisma.CloudflareAccountUpdateWithoutZonesInput, Prisma.CloudflareAccountUncheckedUpdateWithoutZonesInput>
  create: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutZonesInput, Prisma.CloudflareAccountUncheckedCreateWithoutZonesInput>
  where?: Prisma.CloudflareAccountWhereInput
}

export type CloudflareAccountUpdateToOneWithWhereWithoutZonesInput = {
  where?: Prisma.CloudflareAccountWhereInput
  data: Prisma.XOR<Prisma.CloudflareAccountUpdateWithoutZonesInput, Prisma.CloudflareAccountUncheckedUpdateWithoutZonesInput>
}

export type CloudflareAccountUpdateWithoutZonesInput = {
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tunnels?: Prisma.CloudflareTunnelUpdateManyWithoutAccountNestedInput
}

export type CloudflareAccountUncheckedUpdateWithoutZonesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tunnels?: Prisma.CloudflareTunnelUncheckedUpdateManyWithoutAccountNestedInput
}

export type CloudflareAccountCreateWithoutTunnelsInput = {
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  zones?: Prisma.ZoneCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountUncheckedCreateWithoutTunnelsInput = {
  id?: number
  providerType?: string
  label: string
  email?: string | null
  apiToken: string
  createdAt?: Date | string
  zones?: Prisma.ZoneUncheckedCreateNestedManyWithoutAccountInput
}

export type CloudflareAccountCreateOrConnectWithoutTunnelsInput = {
  where: Prisma.CloudflareAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedCreateWithoutTunnelsInput>
}

export type CloudflareAccountUpsertWithoutTunnelsInput = {
  update: Prisma.XOR<Prisma.CloudflareAccountUpdateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedUpdateWithoutTunnelsInput>
  create: Prisma.XOR<Prisma.CloudflareAccountCreateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedCreateWithoutTunnelsInput>
  where?: Prisma.CloudflareAccountWhereInput
}

export type CloudflareAccountUpdateToOneWithWhereWithoutTunnelsInput = {
  where?: Prisma.CloudflareAccountWhereInput
  data: Prisma.XOR<Prisma.CloudflareAccountUpdateWithoutTunnelsInput, Prisma.CloudflareAccountUncheckedUpdateWithoutTunnelsInput>
}

export type CloudflareAccountUpdateWithoutTunnelsInput = {
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  zones?: Prisma.ZoneUpdateManyWithoutAccountNestedInput
}

export type CloudflareAccountUncheckedUpdateWithoutTunnelsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  providerType?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  apiToken?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  zones?: Prisma.ZoneUncheckedUpdateManyWithoutAccountNestedInput
}


/**
 * Count Type CloudflareAccountCountOutputType
 */

export type CloudflareAccountCountOutputType = {
  zones: number
  tunnels: number
}

export type CloudflareAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zones?: boolean | CloudflareAccountCountOutputTypeCountZonesArgs
  tunnels?: boolean | CloudflareAccountCountOutputTypeCountTunnelsArgs
}

/**
 * CloudflareAccountCountOutputType without action
 */
export type CloudflareAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccountCountOutputType
   */
  select?: Prisma.CloudflareAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CloudflareAccountCountOutputType without action
 */
export type CloudflareAccountCountOutputTypeCountZonesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ZoneWhereInput
}

/**
 * CloudflareAccountCountOutputType without action
 */
export type CloudflareAccountCountOutputTypeCountTunnelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CloudflareTunnelWhereInput
}


export type CloudflareAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  providerType?: boolean
  label?: boolean
  email?: boolean
  apiToken?: boolean
  createdAt?: boolean
  zones?: boolean | Prisma.CloudflareAccount$zonesArgs<ExtArgs>
  tunnels?: boolean | Prisma.CloudflareAccount$tunnelsArgs<ExtArgs>
  _count?: boolean | Prisma.CloudflareAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cloudflareAccount"]>

export type CloudflareAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  providerType?: boolean
  label?: boolean
  email?: boolean
  apiToken?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["cloudflareAccount"]>

export type CloudflareAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  providerType?: boolean
  label?: boolean
  email?: boolean
  apiToken?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["cloudflareAccount"]>

export type CloudflareAccountSelectScalar = {
  id?: boolean
  providerType?: boolean
  label?: boolean
  email?: boolean
  apiToken?: boolean
  createdAt?: boolean
}

export type CloudflareAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "providerType" | "label" | "email" | "apiToken" | "createdAt", ExtArgs["result"]["cloudflareAccount"]>
export type CloudflareAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zones?: boolean | Prisma.CloudflareAccount$zonesArgs<ExtArgs>
  tunnels?: boolean | Prisma.CloudflareAccount$tunnelsArgs<ExtArgs>
  _count?: boolean | Prisma.CloudflareAccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type CloudflareAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type CloudflareAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $CloudflareAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CloudflareAccount"
  objects: {
    zones: Prisma.$ZonePayload<ExtArgs>[]
    tunnels: Prisma.$CloudflareTunnelPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    providerType: string
    label: string
    email: string | null
    apiToken: string
    createdAt: Date
  }, ExtArgs["result"]["cloudflareAccount"]>
  composites: {}
}

export type CloudflareAccountGetPayload<S extends boolean | null | undefined | CloudflareAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload, S>

export type CloudflareAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CloudflareAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CloudflareAccountCountAggregateInputType | true
  }

export interface CloudflareAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CloudflareAccount'], meta: { name: 'CloudflareAccount' } }
  /**
   * Find zero or one CloudflareAccount that matches the filter.
   * @param {CloudflareAccountFindUniqueArgs} args - Arguments to find a CloudflareAccount
   * @example
   * // Get one CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CloudflareAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, CloudflareAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CloudflareAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CloudflareAccountFindUniqueOrThrowArgs} args - Arguments to find a CloudflareAccount
   * @example
   * // Get one CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CloudflareAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CloudflareAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CloudflareAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountFindFirstArgs} args - Arguments to find a CloudflareAccount
   * @example
   * // Get one CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CloudflareAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CloudflareAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountFindFirstOrThrowArgs} args - Arguments to find a CloudflareAccount
   * @example
   * // Get one CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CloudflareAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CloudflareAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CloudflareAccounts
   * const cloudflareAccounts = await prisma.cloudflareAccount.findMany()
   * 
   * // Get first 10 CloudflareAccounts
   * const cloudflareAccounts = await prisma.cloudflareAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cloudflareAccountWithIdOnly = await prisma.cloudflareAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CloudflareAccountFindManyArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CloudflareAccount.
   * @param {CloudflareAccountCreateArgs} args - Arguments to create a CloudflareAccount.
   * @example
   * // Create one CloudflareAccount
   * const CloudflareAccount = await prisma.cloudflareAccount.create({
   *   data: {
   *     // ... data to create a CloudflareAccount
   *   }
   * })
   * 
   */
  create<T extends CloudflareAccountCreateArgs>(args: Prisma.SelectSubset<T, CloudflareAccountCreateArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CloudflareAccounts.
   * @param {CloudflareAccountCreateManyArgs} args - Arguments to create many CloudflareAccounts.
   * @example
   * // Create many CloudflareAccounts
   * const cloudflareAccount = await prisma.cloudflareAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CloudflareAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CloudflareAccounts and returns the data saved in the database.
   * @param {CloudflareAccountCreateManyAndReturnArgs} args - Arguments to create many CloudflareAccounts.
   * @example
   * // Create many CloudflareAccounts
   * const cloudflareAccount = await prisma.cloudflareAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CloudflareAccounts and only return the `id`
   * const cloudflareAccountWithIdOnly = await prisma.cloudflareAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CloudflareAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CloudflareAccount.
   * @param {CloudflareAccountDeleteArgs} args - Arguments to delete one CloudflareAccount.
   * @example
   * // Delete one CloudflareAccount
   * const CloudflareAccount = await prisma.cloudflareAccount.delete({
   *   where: {
   *     // ... filter to delete one CloudflareAccount
   *   }
   * })
   * 
   */
  delete<T extends CloudflareAccountDeleteArgs>(args: Prisma.SelectSubset<T, CloudflareAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CloudflareAccount.
   * @param {CloudflareAccountUpdateArgs} args - Arguments to update one CloudflareAccount.
   * @example
   * // Update one CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CloudflareAccountUpdateArgs>(args: Prisma.SelectSubset<T, CloudflareAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CloudflareAccounts.
   * @param {CloudflareAccountDeleteManyArgs} args - Arguments to filter CloudflareAccounts to delete.
   * @example
   * // Delete a few CloudflareAccounts
   * const { count } = await prisma.cloudflareAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CloudflareAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, CloudflareAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CloudflareAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CloudflareAccounts
   * const cloudflareAccount = await prisma.cloudflareAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CloudflareAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, CloudflareAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CloudflareAccounts and returns the data updated in the database.
   * @param {CloudflareAccountUpdateManyAndReturnArgs} args - Arguments to update many CloudflareAccounts.
   * @example
   * // Update many CloudflareAccounts
   * const cloudflareAccount = await prisma.cloudflareAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CloudflareAccounts and only return the `id`
   * const cloudflareAccountWithIdOnly = await prisma.cloudflareAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CloudflareAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CloudflareAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CloudflareAccount.
   * @param {CloudflareAccountUpsertArgs} args - Arguments to update or create a CloudflareAccount.
   * @example
   * // Update or create a CloudflareAccount
   * const cloudflareAccount = await prisma.cloudflareAccount.upsert({
   *   create: {
   *     // ... data to create a CloudflareAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CloudflareAccount we want to update
   *   }
   * })
   */
  upsert<T extends CloudflareAccountUpsertArgs>(args: Prisma.SelectSubset<T, CloudflareAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__CloudflareAccountClient<runtime.Types.Result.GetResult<Prisma.$CloudflareAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CloudflareAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountCountArgs} args - Arguments to filter CloudflareAccounts to count.
   * @example
   * // Count the number of CloudflareAccounts
   * const count = await prisma.cloudflareAccount.count({
   *   where: {
   *     // ... the filter for the CloudflareAccounts we want to count
   *   }
   * })
  **/
  count<T extends CloudflareAccountCountArgs>(
    args?: Prisma.Subset<T, CloudflareAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CloudflareAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CloudflareAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CloudflareAccountAggregateArgs>(args: Prisma.Subset<T, CloudflareAccountAggregateArgs>): Prisma.PrismaPromise<GetCloudflareAccountAggregateType<T>>

  /**
   * Group by CloudflareAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CloudflareAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CloudflareAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CloudflareAccountGroupByArgs['orderBy'] }
      : { orderBy?: CloudflareAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CloudflareAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCloudflareAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CloudflareAccount model
 */
readonly fields: CloudflareAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CloudflareAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CloudflareAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  zones<T extends Prisma.CloudflareAccount$zonesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CloudflareAccount$zonesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ZonePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tunnels<T extends Prisma.CloudflareAccount$tunnelsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CloudflareAccount$tunnelsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CloudflareTunnelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CloudflareAccount model
 */
export interface CloudflareAccountFieldRefs {
  readonly id: Prisma.FieldRef<"CloudflareAccount", 'Int'>
  readonly providerType: Prisma.FieldRef<"CloudflareAccount", 'String'>
  readonly label: Prisma.FieldRef<"CloudflareAccount", 'String'>
  readonly email: Prisma.FieldRef<"CloudflareAccount", 'String'>
  readonly apiToken: Prisma.FieldRef<"CloudflareAccount", 'String'>
  readonly createdAt: Prisma.FieldRef<"CloudflareAccount", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CloudflareAccount findUnique
 */
export type CloudflareAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareAccount to fetch.
   */
  where: Prisma.CloudflareAccountWhereUniqueInput
}

/**
 * CloudflareAccount findUniqueOrThrow
 */
export type CloudflareAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareAccount to fetch.
   */
  where: Prisma.CloudflareAccountWhereUniqueInput
}

/**
 * CloudflareAccount findFirst
 */
export type CloudflareAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareAccount to fetch.
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareAccounts to fetch.
   */
  orderBy?: Prisma.CloudflareAccountOrderByWithRelationInput | Prisma.CloudflareAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CloudflareAccounts.
   */
  cursor?: Prisma.CloudflareAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareAccounts.
   */
  distinct?: Prisma.CloudflareAccountScalarFieldEnum | Prisma.CloudflareAccountScalarFieldEnum[]
}

/**
 * CloudflareAccount findFirstOrThrow
 */
export type CloudflareAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareAccount to fetch.
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareAccounts to fetch.
   */
  orderBy?: Prisma.CloudflareAccountOrderByWithRelationInput | Prisma.CloudflareAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CloudflareAccounts.
   */
  cursor?: Prisma.CloudflareAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareAccounts.
   */
  distinct?: Prisma.CloudflareAccountScalarFieldEnum | Prisma.CloudflareAccountScalarFieldEnum[]
}

/**
 * CloudflareAccount findMany
 */
export type CloudflareAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter, which CloudflareAccounts to fetch.
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CloudflareAccounts to fetch.
   */
  orderBy?: Prisma.CloudflareAccountOrderByWithRelationInput | Prisma.CloudflareAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CloudflareAccounts.
   */
  cursor?: Prisma.CloudflareAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CloudflareAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CloudflareAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CloudflareAccounts.
   */
  distinct?: Prisma.CloudflareAccountScalarFieldEnum | Prisma.CloudflareAccountScalarFieldEnum[]
}

/**
 * CloudflareAccount create
 */
export type CloudflareAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a CloudflareAccount.
   */
  data: Prisma.XOR<Prisma.CloudflareAccountCreateInput, Prisma.CloudflareAccountUncheckedCreateInput>
}

/**
 * CloudflareAccount createMany
 */
export type CloudflareAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CloudflareAccounts.
   */
  data: Prisma.CloudflareAccountCreateManyInput | Prisma.CloudflareAccountCreateManyInput[]
}

/**
 * CloudflareAccount createManyAndReturn
 */
export type CloudflareAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * The data used to create many CloudflareAccounts.
   */
  data: Prisma.CloudflareAccountCreateManyInput | Prisma.CloudflareAccountCreateManyInput[]
}

/**
 * CloudflareAccount update
 */
export type CloudflareAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a CloudflareAccount.
   */
  data: Prisma.XOR<Prisma.CloudflareAccountUpdateInput, Prisma.CloudflareAccountUncheckedUpdateInput>
  /**
   * Choose, which CloudflareAccount to update.
   */
  where: Prisma.CloudflareAccountWhereUniqueInput
}

/**
 * CloudflareAccount updateMany
 */
export type CloudflareAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CloudflareAccounts.
   */
  data: Prisma.XOR<Prisma.CloudflareAccountUpdateManyMutationInput, Prisma.CloudflareAccountUncheckedUpdateManyInput>
  /**
   * Filter which CloudflareAccounts to update
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * Limit how many CloudflareAccounts to update.
   */
  limit?: number
}

/**
 * CloudflareAccount updateManyAndReturn
 */
export type CloudflareAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * The data used to update CloudflareAccounts.
   */
  data: Prisma.XOR<Prisma.CloudflareAccountUpdateManyMutationInput, Prisma.CloudflareAccountUncheckedUpdateManyInput>
  /**
   * Filter which CloudflareAccounts to update
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * Limit how many CloudflareAccounts to update.
   */
  limit?: number
}

/**
 * CloudflareAccount upsert
 */
export type CloudflareAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the CloudflareAccount to update in case it exists.
   */
  where: Prisma.CloudflareAccountWhereUniqueInput
  /**
   * In case the CloudflareAccount found by the `where` argument doesn't exist, create a new CloudflareAccount with this data.
   */
  create: Prisma.XOR<Prisma.CloudflareAccountCreateInput, Prisma.CloudflareAccountUncheckedCreateInput>
  /**
   * In case the CloudflareAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CloudflareAccountUpdateInput, Prisma.CloudflareAccountUncheckedUpdateInput>
}

/**
 * CloudflareAccount delete
 */
export type CloudflareAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
  /**
   * Filter which CloudflareAccount to delete.
   */
  where: Prisma.CloudflareAccountWhereUniqueInput
}

/**
 * CloudflareAccount deleteMany
 */
export type CloudflareAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CloudflareAccounts to delete
   */
  where?: Prisma.CloudflareAccountWhereInput
  /**
   * Limit how many CloudflareAccounts to delete.
   */
  limit?: number
}

/**
 * CloudflareAccount.zones
 */
export type CloudflareAccount$zonesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Zone
   */
  select?: Prisma.ZoneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Zone
   */
  omit?: Prisma.ZoneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ZoneInclude<ExtArgs> | null
  where?: Prisma.ZoneWhereInput
  orderBy?: Prisma.ZoneOrderByWithRelationInput | Prisma.ZoneOrderByWithRelationInput[]
  cursor?: Prisma.ZoneWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ZoneScalarFieldEnum | Prisma.ZoneScalarFieldEnum[]
}

/**
 * CloudflareAccount.tunnels
 */
export type CloudflareAccount$tunnelsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareTunnel
   */
  select?: Prisma.CloudflareTunnelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareTunnel
   */
  omit?: Prisma.CloudflareTunnelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareTunnelInclude<ExtArgs> | null
  where?: Prisma.CloudflareTunnelWhereInput
  orderBy?: Prisma.CloudflareTunnelOrderByWithRelationInput | Prisma.CloudflareTunnelOrderByWithRelationInput[]
  cursor?: Prisma.CloudflareTunnelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CloudflareTunnelScalarFieldEnum | Prisma.CloudflareTunnelScalarFieldEnum[]
}

/**
 * CloudflareAccount without action
 */
export type CloudflareAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CloudflareAccount
   */
  select?: Prisma.CloudflareAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CloudflareAccount
   */
  omit?: Prisma.CloudflareAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CloudflareAccountInclude<ExtArgs> | null
}
