
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DnsRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DnsRecord
 * 
 */
export type DnsRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$DnsRecordPayload>

export type AggregateDnsRecord = {
  _count: DnsRecordCountAggregateOutputType | null
  _avg: DnsRecordAvgAggregateOutputType | null
  _sum: DnsRecordSumAggregateOutputType | null
  _min: DnsRecordMinAggregateOutputType | null
  _max: DnsRecordMaxAggregateOutputType | null
}

export type DnsRecordAvgAggregateOutputType = {
  id: number | null
  zoneId: number | null
}

export type DnsRecordSumAggregateOutputType = {
  id: number | null
  zoneId: number | null
}

export type DnsRecordMinAggregateOutputType = {
  id: number | null
  cfRecordId: string | null
  name: string | null
  type: string | null
  content: string | null
  isAutoUpdate: boolean | null
  proxied: boolean | null
  updateToken: string | null
  zoneId: number | null
}

export type DnsRecordMaxAggregateOutputType = {
  id: number | null
  cfRecordId: string | null
  name: string | null
  type: string | null
  content: string | null
  isAutoUpdate: boolean | null
  proxied: boolean | null
  updateToken: string | null
  zoneId: number | null
}

export type DnsRecordCountAggregateOutputType = {
  id: number
  cfRecordId: number
  name: number
  type: number
  content: number
  isAutoUpdate: number
  proxied: number
  updateToken: number
  zoneId: number
  _all: number
}


export type DnsRecordAvgAggregateInputType = {
  id?: true
  zoneId?: true
}

export type DnsRecordSumAggregateInputType = {
  id?: true
  zoneId?: true
}

export type DnsRecordMinAggregateInputType = {
  id?: true
  cfRecordId?: true
  name?: true
  type?: true
  content?: true
  isAutoUpdate?: true
  proxied?: true
  updateToken?: true
  zoneId?: true
}

export type DnsRecordMaxAggregateInputType = {
  id?: true
  cfRecordId?: true
  name?: true
  type?: true
  content?: true
  isAutoUpdate?: true
  proxied?: true
  updateToken?: true
  zoneId?: true
}

export type DnsRecordCountAggregateInputType = {
  id?: true
  cfRecordId?: true
  name?: true
  type?: true
  content?: true
  isAutoUpdate?: true
  proxied?: true
  updateToken?: true
  zoneId?: true
  _all?: true
}

export type DnsRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DnsRecord to aggregate.
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DnsRecords to fetch.
   */
  orderBy?: Prisma.DnsRecordOrderByWithRelationInput | Prisma.DnsRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DnsRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DnsRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DnsRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DnsRecords
  **/
  _count?: true | DnsRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DnsRecordAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DnsRecordSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DnsRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DnsRecordMaxAggregateInputType
}

export type GetDnsRecordAggregateType<T extends DnsRecordAggregateArgs> = {
      [P in keyof T & keyof AggregateDnsRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDnsRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateDnsRecord[P]>
}




export type DnsRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DnsRecordWhereInput
  orderBy?: Prisma.DnsRecordOrderByWithAggregationInput | Prisma.DnsRecordOrderByWithAggregationInput[]
  by: Prisma.DnsRecordScalarFieldEnum[] | Prisma.DnsRecordScalarFieldEnum
  having?: Prisma.DnsRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DnsRecordCountAggregateInputType | true
  _avg?: DnsRecordAvgAggregateInputType
  _sum?: DnsRecordSumAggregateInputType
  _min?: DnsRecordMinAggregateInputType
  _max?: DnsRecordMaxAggregateInputType
}

export type DnsRecordGroupByOutputType = {
  id: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate: boolean
  proxied: boolean
  updateToken: string | null
  zoneId: number
  _count: DnsRecordCountAggregateOutputType | null
  _avg: DnsRecordAvgAggregateOutputType | null
  _sum: DnsRecordSumAggregateOutputType | null
  _min: DnsRecordMinAggregateOutputType | null
  _max: DnsRecordMaxAggregateOutputType | null
}

type GetDnsRecordGroupByPayload<T extends DnsRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DnsRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DnsRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DnsRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DnsRecordGroupByOutputType[P]>
      }
    >
  >



export type DnsRecordWhereInput = {
  AND?: Prisma.DnsRecordWhereInput | Prisma.DnsRecordWhereInput[]
  OR?: Prisma.DnsRecordWhereInput[]
  NOT?: Prisma.DnsRecordWhereInput | Prisma.DnsRecordWhereInput[]
  id?: Prisma.IntFilter<"DnsRecord"> | number
  cfRecordId?: Prisma.StringFilter<"DnsRecord"> | string
  name?: Prisma.StringFilter<"DnsRecord"> | string
  type?: Prisma.StringFilter<"DnsRecord"> | string
  content?: Prisma.StringFilter<"DnsRecord"> | string
  isAutoUpdate?: Prisma.BoolFilter<"DnsRecord"> | boolean
  proxied?: Prisma.BoolFilter<"DnsRecord"> | boolean
  updateToken?: Prisma.StringNullableFilter<"DnsRecord"> | string | null
  zoneId?: Prisma.IntFilter<"DnsRecord"> | number
  zone?: Prisma.XOR<Prisma.ZoneScalarRelationFilter, Prisma.ZoneWhereInput>
  updateLogs?: Prisma.UpdateLogListRelationFilter
}

export type DnsRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cfRecordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  content?: Prisma.SortOrder
  isAutoUpdate?: Prisma.SortOrder
  proxied?: Prisma.SortOrder
  updateToken?: Prisma.SortOrderInput | Prisma.SortOrder
  zoneId?: Prisma.SortOrder
  zone?: Prisma.ZoneOrderByWithRelationInput
  updateLogs?: Prisma.UpdateLogOrderByRelationAggregateInput
}

export type DnsRecordWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  cfRecordId?: string
  updateToken?: string
  AND?: Prisma.DnsRecordWhereInput | Prisma.DnsRecordWhereInput[]
  OR?: Prisma.DnsRecordWhereInput[]
  NOT?: Prisma.DnsRecordWhereInput | Prisma.DnsRecordWhereInput[]
  name?: Prisma.StringFilter<"DnsRecord"> | string
  type?: Prisma.StringFilter<"DnsRecord"> | string
  content?: Prisma.StringFilter<"DnsRecord"> | string
  isAutoUpdate?: Prisma.BoolFilter<"DnsRecord"> | boolean
  proxied?: Prisma.BoolFilter<"DnsRecord"> | boolean
  zoneId?: Prisma.IntFilter<"DnsRecord"> | number
  zone?: Prisma.XOR<Prisma.ZoneScalarRelationFilter, Prisma.ZoneWhereInput>
  updateLogs?: Prisma.UpdateLogListRelationFilter
}, "id" | "cfRecordId" | "updateToken">

export type DnsRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cfRecordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  content?: Prisma.SortOrder
  isAutoUpdate?: Prisma.SortOrder
  proxied?: Prisma.SortOrder
  updateToken?: Prisma.SortOrderInput | Prisma.SortOrder
  zoneId?: Prisma.SortOrder
  _count?: Prisma.DnsRecordCountOrderByAggregateInput
  _avg?: Prisma.DnsRecordAvgOrderByAggregateInput
  _max?: Prisma.DnsRecordMaxOrderByAggregateInput
  _min?: Prisma.DnsRecordMinOrderByAggregateInput
  _sum?: Prisma.DnsRecordSumOrderByAggregateInput
}

export type DnsRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.DnsRecordScalarWhereWithAggregatesInput | Prisma.DnsRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.DnsRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DnsRecordScalarWhereWithAggregatesInput | Prisma.DnsRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"DnsRecord"> | number
  cfRecordId?: Prisma.StringWithAggregatesFilter<"DnsRecord"> | string
  name?: Prisma.StringWithAggregatesFilter<"DnsRecord"> | string
  type?: Prisma.StringWithAggregatesFilter<"DnsRecord"> | string
  content?: Prisma.StringWithAggregatesFilter<"DnsRecord"> | string
  isAutoUpdate?: Prisma.BoolWithAggregatesFilter<"DnsRecord"> | boolean
  proxied?: Prisma.BoolWithAggregatesFilter<"DnsRecord"> | boolean
  updateToken?: Prisma.StringNullableWithAggregatesFilter<"DnsRecord"> | string | null
  zoneId?: Prisma.IntWithAggregatesFilter<"DnsRecord"> | number
}

export type DnsRecordCreateInput = {
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  zone: Prisma.ZoneCreateNestedOneWithoutRecordsInput
  updateLogs?: Prisma.UpdateLogCreateNestedManyWithoutRecordInput
}

export type DnsRecordUncheckedCreateInput = {
  id?: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  zoneId: number
  updateLogs?: Prisma.UpdateLogUncheckedCreateNestedManyWithoutRecordInput
}

export type DnsRecordUpdateInput = {
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zone?: Prisma.ZoneUpdateOneRequiredWithoutRecordsNestedInput
  updateLogs?: Prisma.UpdateLogUpdateManyWithoutRecordNestedInput
}

export type DnsRecordUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneId?: Prisma.IntFieldUpdateOperationsInput | number
  updateLogs?: Prisma.UpdateLogUncheckedUpdateManyWithoutRecordNestedInput
}

export type DnsRecordCreateManyInput = {
  id?: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  zoneId: number
}

export type DnsRecordUpdateManyMutationInput = {
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DnsRecordUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DnsRecordListRelationFilter = {
  every?: Prisma.DnsRecordWhereInput
  some?: Prisma.DnsRecordWhereInput
  none?: Prisma.DnsRecordWhereInput
}

export type DnsRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DnsRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cfRecordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  content?: Prisma.SortOrder
  isAutoUpdate?: Prisma.SortOrder
  proxied?: Prisma.SortOrder
  updateToken?: Prisma.SortOrder
  zoneId?: Prisma.SortOrder
}

export type DnsRecordAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  zoneId?: Prisma.SortOrder
}

export type DnsRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cfRecordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  content?: Prisma.SortOrder
  isAutoUpdate?: Prisma.SortOrder
  proxied?: Prisma.SortOrder
  updateToken?: Prisma.SortOrder
  zoneId?: Prisma.SortOrder
}

export type DnsRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cfRecordId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  content?: Prisma.SortOrder
  isAutoUpdate?: Prisma.SortOrder
  proxied?: Prisma.SortOrder
  updateToken?: Prisma.SortOrder
  zoneId?: Prisma.SortOrder
}

export type DnsRecordSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  zoneId?: Prisma.SortOrder
}

export type DnsRecordScalarRelationFilter = {
  is?: Prisma.DnsRecordWhereInput
  isNot?: Prisma.DnsRecordWhereInput
}

export type DnsRecordCreateNestedManyWithoutZoneInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput> | Prisma.DnsRecordCreateWithoutZoneInput[] | Prisma.DnsRecordUncheckedCreateWithoutZoneInput[]
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutZoneInput | Prisma.DnsRecordCreateOrConnectWithoutZoneInput[]
  createMany?: Prisma.DnsRecordCreateManyZoneInputEnvelope
  connect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
}

export type DnsRecordUncheckedCreateNestedManyWithoutZoneInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput> | Prisma.DnsRecordCreateWithoutZoneInput[] | Prisma.DnsRecordUncheckedCreateWithoutZoneInput[]
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutZoneInput | Prisma.DnsRecordCreateOrConnectWithoutZoneInput[]
  createMany?: Prisma.DnsRecordCreateManyZoneInputEnvelope
  connect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
}

export type DnsRecordUpdateManyWithoutZoneNestedInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput> | Prisma.DnsRecordCreateWithoutZoneInput[] | Prisma.DnsRecordUncheckedCreateWithoutZoneInput[]
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutZoneInput | Prisma.DnsRecordCreateOrConnectWithoutZoneInput[]
  upsert?: Prisma.DnsRecordUpsertWithWhereUniqueWithoutZoneInput | Prisma.DnsRecordUpsertWithWhereUniqueWithoutZoneInput[]
  createMany?: Prisma.DnsRecordCreateManyZoneInputEnvelope
  set?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  disconnect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  delete?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  connect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  update?: Prisma.DnsRecordUpdateWithWhereUniqueWithoutZoneInput | Prisma.DnsRecordUpdateWithWhereUniqueWithoutZoneInput[]
  updateMany?: Prisma.DnsRecordUpdateManyWithWhereWithoutZoneInput | Prisma.DnsRecordUpdateManyWithWhereWithoutZoneInput[]
  deleteMany?: Prisma.DnsRecordScalarWhereInput | Prisma.DnsRecordScalarWhereInput[]
}

export type DnsRecordUncheckedUpdateManyWithoutZoneNestedInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput> | Prisma.DnsRecordCreateWithoutZoneInput[] | Prisma.DnsRecordUncheckedCreateWithoutZoneInput[]
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutZoneInput | Prisma.DnsRecordCreateOrConnectWithoutZoneInput[]
  upsert?: Prisma.DnsRecordUpsertWithWhereUniqueWithoutZoneInput | Prisma.DnsRecordUpsertWithWhereUniqueWithoutZoneInput[]
  createMany?: Prisma.DnsRecordCreateManyZoneInputEnvelope
  set?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  disconnect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  delete?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  connect?: Prisma.DnsRecordWhereUniqueInput | Prisma.DnsRecordWhereUniqueInput[]
  update?: Prisma.DnsRecordUpdateWithWhereUniqueWithoutZoneInput | Prisma.DnsRecordUpdateWithWhereUniqueWithoutZoneInput[]
  updateMany?: Prisma.DnsRecordUpdateManyWithWhereWithoutZoneInput | Prisma.DnsRecordUpdateManyWithWhereWithoutZoneInput[]
  deleteMany?: Prisma.DnsRecordScalarWhereInput | Prisma.DnsRecordScalarWhereInput[]
}

export type DnsRecordCreateNestedOneWithoutUpdateLogsInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedCreateWithoutUpdateLogsInput>
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutUpdateLogsInput
  connect?: Prisma.DnsRecordWhereUniqueInput
}

export type DnsRecordUpdateOneRequiredWithoutUpdateLogsNestedInput = {
  create?: Prisma.XOR<Prisma.DnsRecordCreateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedCreateWithoutUpdateLogsInput>
  connectOrCreate?: Prisma.DnsRecordCreateOrConnectWithoutUpdateLogsInput
  upsert?: Prisma.DnsRecordUpsertWithoutUpdateLogsInput
  connect?: Prisma.DnsRecordWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DnsRecordUpdateToOneWithWhereWithoutUpdateLogsInput, Prisma.DnsRecordUpdateWithoutUpdateLogsInput>, Prisma.DnsRecordUncheckedUpdateWithoutUpdateLogsInput>
}

export type DnsRecordCreateWithoutZoneInput = {
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  updateLogs?: Prisma.UpdateLogCreateNestedManyWithoutRecordInput
}

export type DnsRecordUncheckedCreateWithoutZoneInput = {
  id?: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  updateLogs?: Prisma.UpdateLogUncheckedCreateNestedManyWithoutRecordInput
}

export type DnsRecordCreateOrConnectWithoutZoneInput = {
  where: Prisma.DnsRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput>
}

export type DnsRecordCreateManyZoneInputEnvelope = {
  data: Prisma.DnsRecordCreateManyZoneInput | Prisma.DnsRecordCreateManyZoneInput[]
}

export type DnsRecordUpsertWithWhereUniqueWithoutZoneInput = {
  where: Prisma.DnsRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.DnsRecordUpdateWithoutZoneInput, Prisma.DnsRecordUncheckedUpdateWithoutZoneInput>
  create: Prisma.XOR<Prisma.DnsRecordCreateWithoutZoneInput, Prisma.DnsRecordUncheckedCreateWithoutZoneInput>
}

export type DnsRecordUpdateWithWhereUniqueWithoutZoneInput = {
  where: Prisma.DnsRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.DnsRecordUpdateWithoutZoneInput, Prisma.DnsRecordUncheckedUpdateWithoutZoneInput>
}

export type DnsRecordUpdateManyWithWhereWithoutZoneInput = {
  where: Prisma.DnsRecordScalarWhereInput
  data: Prisma.XOR<Prisma.DnsRecordUpdateManyMutationInput, Prisma.DnsRecordUncheckedUpdateManyWithoutZoneInput>
}

export type DnsRecordScalarWhereInput = {
  AND?: Prisma.DnsRecordScalarWhereInput | Prisma.DnsRecordScalarWhereInput[]
  OR?: Prisma.DnsRecordScalarWhereInput[]
  NOT?: Prisma.DnsRecordScalarWhereInput | Prisma.DnsRecordScalarWhereInput[]
  id?: Prisma.IntFilter<"DnsRecord"> | number
  cfRecordId?: Prisma.StringFilter<"DnsRecord"> | string
  name?: Prisma.StringFilter<"DnsRecord"> | string
  type?: Prisma.StringFilter<"DnsRecord"> | string
  content?: Prisma.StringFilter<"DnsRecord"> | string
  isAutoUpdate?: Prisma.BoolFilter<"DnsRecord"> | boolean
  proxied?: Prisma.BoolFilter<"DnsRecord"> | boolean
  updateToken?: Prisma.StringNullableFilter<"DnsRecord"> | string | null
  zoneId?: Prisma.IntFilter<"DnsRecord"> | number
}

export type DnsRecordCreateWithoutUpdateLogsInput = {
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  zone: Prisma.ZoneCreateNestedOneWithoutRecordsInput
}

export type DnsRecordUncheckedCreateWithoutUpdateLogsInput = {
  id?: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
  zoneId: number
}

export type DnsRecordCreateOrConnectWithoutUpdateLogsInput = {
  where: Prisma.DnsRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.DnsRecordCreateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedCreateWithoutUpdateLogsInput>
}

export type DnsRecordUpsertWithoutUpdateLogsInput = {
  update: Prisma.XOR<Prisma.DnsRecordUpdateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedUpdateWithoutUpdateLogsInput>
  create: Prisma.XOR<Prisma.DnsRecordCreateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedCreateWithoutUpdateLogsInput>
  where?: Prisma.DnsRecordWhereInput
}

export type DnsRecordUpdateToOneWithWhereWithoutUpdateLogsInput = {
  where?: Prisma.DnsRecordWhereInput
  data: Prisma.XOR<Prisma.DnsRecordUpdateWithoutUpdateLogsInput, Prisma.DnsRecordUncheckedUpdateWithoutUpdateLogsInput>
}

export type DnsRecordUpdateWithoutUpdateLogsInput = {
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zone?: Prisma.ZoneUpdateOneRequiredWithoutRecordsNestedInput
}

export type DnsRecordUncheckedUpdateWithoutUpdateLogsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  zoneId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DnsRecordCreateManyZoneInput = {
  id?: number
  cfRecordId: string
  name: string
  type: string
  content: string
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: string | null
}

export type DnsRecordUpdateWithoutZoneInput = {
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updateLogs?: Prisma.UpdateLogUpdateManyWithoutRecordNestedInput
}

export type DnsRecordUncheckedUpdateWithoutZoneInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updateLogs?: Prisma.UpdateLogUncheckedUpdateManyWithoutRecordNestedInput
}

export type DnsRecordUncheckedUpdateManyWithoutZoneInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cfRecordId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  isAutoUpdate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  proxied?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updateToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type DnsRecordCountOutputType
 */

export type DnsRecordCountOutputType = {
  updateLogs: number
}

export type DnsRecordCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updateLogs?: boolean | DnsRecordCountOutputTypeCountUpdateLogsArgs
}

/**
 * DnsRecordCountOutputType without action
 */
export type DnsRecordCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecordCountOutputType
   */
  select?: Prisma.DnsRecordCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DnsRecordCountOutputType without action
 */
export type DnsRecordCountOutputTypeCountUpdateLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UpdateLogWhereInput
}


export type DnsRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cfRecordId?: boolean
  name?: boolean
  type?: boolean
  content?: boolean
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: boolean
  zoneId?: boolean
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
  updateLogs?: boolean | Prisma.DnsRecord$updateLogsArgs<ExtArgs>
  _count?: boolean | Prisma.DnsRecordCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dnsRecord"]>

export type DnsRecordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cfRecordId?: boolean
  name?: boolean
  type?: boolean
  content?: boolean
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: boolean
  zoneId?: boolean
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dnsRecord"]>

export type DnsRecordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cfRecordId?: boolean
  name?: boolean
  type?: boolean
  content?: boolean
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: boolean
  zoneId?: boolean
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dnsRecord"]>

export type DnsRecordSelectScalar = {
  id?: boolean
  cfRecordId?: boolean
  name?: boolean
  type?: boolean
  content?: boolean
  isAutoUpdate?: boolean
  proxied?: boolean
  updateToken?: boolean
  zoneId?: boolean
}

export type DnsRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cfRecordId" | "name" | "type" | "content" | "isAutoUpdate" | "proxied" | "updateToken" | "zoneId", ExtArgs["result"]["dnsRecord"]>
export type DnsRecordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
  updateLogs?: boolean | Prisma.DnsRecord$updateLogsArgs<ExtArgs>
  _count?: boolean | Prisma.DnsRecordCountOutputTypeDefaultArgs<ExtArgs>
}
export type DnsRecordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
}
export type DnsRecordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  zone?: boolean | Prisma.ZoneDefaultArgs<ExtArgs>
}

export type $DnsRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DnsRecord"
  objects: {
    zone: Prisma.$ZonePayload<ExtArgs>
    updateLogs: Prisma.$UpdateLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    cfRecordId: string
    name: string
    type: string
    content: string
    isAutoUpdate: boolean
    proxied: boolean
    updateToken: string | null
    zoneId: number
  }, ExtArgs["result"]["dnsRecord"]>
  composites: {}
}

export type DnsRecordGetPayload<S extends boolean | null | undefined | DnsRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload, S>

export type DnsRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DnsRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DnsRecordCountAggregateInputType | true
  }

export interface DnsRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DnsRecord'], meta: { name: 'DnsRecord' } }
  /**
   * Find zero or one DnsRecord that matches the filter.
   * @param {DnsRecordFindUniqueArgs} args - Arguments to find a DnsRecord
   * @example
   * // Get one DnsRecord
   * const dnsRecord = await prisma.dnsRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DnsRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, DnsRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DnsRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DnsRecordFindUniqueOrThrowArgs} args - Arguments to find a DnsRecord
   * @example
   * // Get one DnsRecord
   * const dnsRecord = await prisma.dnsRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DnsRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DnsRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DnsRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordFindFirstArgs} args - Arguments to find a DnsRecord
   * @example
   * // Get one DnsRecord
   * const dnsRecord = await prisma.dnsRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DnsRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, DnsRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DnsRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordFindFirstOrThrowArgs} args - Arguments to find a DnsRecord
   * @example
   * // Get one DnsRecord
   * const dnsRecord = await prisma.dnsRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DnsRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DnsRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DnsRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DnsRecords
   * const dnsRecords = await prisma.dnsRecord.findMany()
   * 
   * // Get first 10 DnsRecords
   * const dnsRecords = await prisma.dnsRecord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dnsRecordWithIdOnly = await prisma.dnsRecord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DnsRecordFindManyArgs>(args?: Prisma.SelectSubset<T, DnsRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DnsRecord.
   * @param {DnsRecordCreateArgs} args - Arguments to create a DnsRecord.
   * @example
   * // Create one DnsRecord
   * const DnsRecord = await prisma.dnsRecord.create({
   *   data: {
   *     // ... data to create a DnsRecord
   *   }
   * })
   * 
   */
  create<T extends DnsRecordCreateArgs>(args: Prisma.SelectSubset<T, DnsRecordCreateArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DnsRecords.
   * @param {DnsRecordCreateManyArgs} args - Arguments to create many DnsRecords.
   * @example
   * // Create many DnsRecords
   * const dnsRecord = await prisma.dnsRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DnsRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, DnsRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DnsRecords and returns the data saved in the database.
   * @param {DnsRecordCreateManyAndReturnArgs} args - Arguments to create many DnsRecords.
   * @example
   * // Create many DnsRecords
   * const dnsRecord = await prisma.dnsRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DnsRecords and only return the `id`
   * const dnsRecordWithIdOnly = await prisma.dnsRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DnsRecordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DnsRecordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DnsRecord.
   * @param {DnsRecordDeleteArgs} args - Arguments to delete one DnsRecord.
   * @example
   * // Delete one DnsRecord
   * const DnsRecord = await prisma.dnsRecord.delete({
   *   where: {
   *     // ... filter to delete one DnsRecord
   *   }
   * })
   * 
   */
  delete<T extends DnsRecordDeleteArgs>(args: Prisma.SelectSubset<T, DnsRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DnsRecord.
   * @param {DnsRecordUpdateArgs} args - Arguments to update one DnsRecord.
   * @example
   * // Update one DnsRecord
   * const dnsRecord = await prisma.dnsRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DnsRecordUpdateArgs>(args: Prisma.SelectSubset<T, DnsRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DnsRecords.
   * @param {DnsRecordDeleteManyArgs} args - Arguments to filter DnsRecords to delete.
   * @example
   * // Delete a few DnsRecords
   * const { count } = await prisma.dnsRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DnsRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, DnsRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DnsRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DnsRecords
   * const dnsRecord = await prisma.dnsRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DnsRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, DnsRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DnsRecords and returns the data updated in the database.
   * @param {DnsRecordUpdateManyAndReturnArgs} args - Arguments to update many DnsRecords.
   * @example
   * // Update many DnsRecords
   * const dnsRecord = await prisma.dnsRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DnsRecords and only return the `id`
   * const dnsRecordWithIdOnly = await prisma.dnsRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DnsRecordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DnsRecordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DnsRecord.
   * @param {DnsRecordUpsertArgs} args - Arguments to update or create a DnsRecord.
   * @example
   * // Update or create a DnsRecord
   * const dnsRecord = await prisma.dnsRecord.upsert({
   *   create: {
   *     // ... data to create a DnsRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DnsRecord we want to update
   *   }
   * })
   */
  upsert<T extends DnsRecordUpsertArgs>(args: Prisma.SelectSubset<T, DnsRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DnsRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordCountArgs} args - Arguments to filter DnsRecords to count.
   * @example
   * // Count the number of DnsRecords
   * const count = await prisma.dnsRecord.count({
   *   where: {
   *     // ... the filter for the DnsRecords we want to count
   *   }
   * })
  **/
  count<T extends DnsRecordCountArgs>(
    args?: Prisma.Subset<T, DnsRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DnsRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DnsRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DnsRecordAggregateArgs>(args: Prisma.Subset<T, DnsRecordAggregateArgs>): Prisma.PrismaPromise<GetDnsRecordAggregateType<T>>

  /**
   * Group by DnsRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DnsRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DnsRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DnsRecordGroupByArgs['orderBy'] }
      : { orderBy?: DnsRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DnsRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDnsRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DnsRecord model
 */
readonly fields: DnsRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DnsRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DnsRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  zone<T extends Prisma.ZoneDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ZoneDefaultArgs<ExtArgs>>): Prisma.Prisma__ZoneClient<runtime.Types.Result.GetResult<Prisma.$ZonePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  updateLogs<T extends Prisma.DnsRecord$updateLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DnsRecord$updateLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DnsRecord model
 */
export interface DnsRecordFieldRefs {
  readonly id: Prisma.FieldRef<"DnsRecord", 'Int'>
  readonly cfRecordId: Prisma.FieldRef<"DnsRecord", 'String'>
  readonly name: Prisma.FieldRef<"DnsRecord", 'String'>
  readonly type: Prisma.FieldRef<"DnsRecord", 'String'>
  readonly content: Prisma.FieldRef<"DnsRecord", 'String'>
  readonly isAutoUpdate: Prisma.FieldRef<"DnsRecord", 'Boolean'>
  readonly proxied: Prisma.FieldRef<"DnsRecord", 'Boolean'>
  readonly updateToken: Prisma.FieldRef<"DnsRecord", 'String'>
  readonly zoneId: Prisma.FieldRef<"DnsRecord", 'Int'>
}
    

// Custom InputTypes
/**
 * DnsRecord findUnique
 */
export type DnsRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter, which DnsRecord to fetch.
   */
  where: Prisma.DnsRecordWhereUniqueInput
}

/**
 * DnsRecord findUniqueOrThrow
 */
export type DnsRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter, which DnsRecord to fetch.
   */
  where: Prisma.DnsRecordWhereUniqueInput
}

/**
 * DnsRecord findFirst
 */
export type DnsRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter, which DnsRecord to fetch.
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DnsRecords to fetch.
   */
  orderBy?: Prisma.DnsRecordOrderByWithRelationInput | Prisma.DnsRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DnsRecords.
   */
  cursor?: Prisma.DnsRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DnsRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DnsRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DnsRecords.
   */
  distinct?: Prisma.DnsRecordScalarFieldEnum | Prisma.DnsRecordScalarFieldEnum[]
}

/**
 * DnsRecord findFirstOrThrow
 */
export type DnsRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter, which DnsRecord to fetch.
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DnsRecords to fetch.
   */
  orderBy?: Prisma.DnsRecordOrderByWithRelationInput | Prisma.DnsRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DnsRecords.
   */
  cursor?: Prisma.DnsRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DnsRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DnsRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DnsRecords.
   */
  distinct?: Prisma.DnsRecordScalarFieldEnum | Prisma.DnsRecordScalarFieldEnum[]
}

/**
 * DnsRecord findMany
 */
export type DnsRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter, which DnsRecords to fetch.
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DnsRecords to fetch.
   */
  orderBy?: Prisma.DnsRecordOrderByWithRelationInput | Prisma.DnsRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DnsRecords.
   */
  cursor?: Prisma.DnsRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DnsRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DnsRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DnsRecords.
   */
  distinct?: Prisma.DnsRecordScalarFieldEnum | Prisma.DnsRecordScalarFieldEnum[]
}

/**
 * DnsRecord create
 */
export type DnsRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a DnsRecord.
   */
  data: Prisma.XOR<Prisma.DnsRecordCreateInput, Prisma.DnsRecordUncheckedCreateInput>
}

/**
 * DnsRecord createMany
 */
export type DnsRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DnsRecords.
   */
  data: Prisma.DnsRecordCreateManyInput | Prisma.DnsRecordCreateManyInput[]
}

/**
 * DnsRecord createManyAndReturn
 */
export type DnsRecordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * The data used to create many DnsRecords.
   */
  data: Prisma.DnsRecordCreateManyInput | Prisma.DnsRecordCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DnsRecord update
 */
export type DnsRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a DnsRecord.
   */
  data: Prisma.XOR<Prisma.DnsRecordUpdateInput, Prisma.DnsRecordUncheckedUpdateInput>
  /**
   * Choose, which DnsRecord to update.
   */
  where: Prisma.DnsRecordWhereUniqueInput
}

/**
 * DnsRecord updateMany
 */
export type DnsRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DnsRecords.
   */
  data: Prisma.XOR<Prisma.DnsRecordUpdateManyMutationInput, Prisma.DnsRecordUncheckedUpdateManyInput>
  /**
   * Filter which DnsRecords to update
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * Limit how many DnsRecords to update.
   */
  limit?: number
}

/**
 * DnsRecord updateManyAndReturn
 */
export type DnsRecordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * The data used to update DnsRecords.
   */
  data: Prisma.XOR<Prisma.DnsRecordUpdateManyMutationInput, Prisma.DnsRecordUncheckedUpdateManyInput>
  /**
   * Filter which DnsRecords to update
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * Limit how many DnsRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DnsRecord upsert
 */
export type DnsRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the DnsRecord to update in case it exists.
   */
  where: Prisma.DnsRecordWhereUniqueInput
  /**
   * In case the DnsRecord found by the `where` argument doesn't exist, create a new DnsRecord with this data.
   */
  create: Prisma.XOR<Prisma.DnsRecordCreateInput, Prisma.DnsRecordUncheckedCreateInput>
  /**
   * In case the DnsRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DnsRecordUpdateInput, Prisma.DnsRecordUncheckedUpdateInput>
}

/**
 * DnsRecord delete
 */
export type DnsRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
  /**
   * Filter which DnsRecord to delete.
   */
  where: Prisma.DnsRecordWhereUniqueInput
}

/**
 * DnsRecord deleteMany
 */
export type DnsRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DnsRecords to delete
   */
  where?: Prisma.DnsRecordWhereInput
  /**
   * Limit how many DnsRecords to delete.
   */
  limit?: number
}

/**
 * DnsRecord.updateLogs
 */
export type DnsRecord$updateLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  where?: Prisma.UpdateLogWhereInput
  orderBy?: Prisma.UpdateLogOrderByWithRelationInput | Prisma.UpdateLogOrderByWithRelationInput[]
  cursor?: Prisma.UpdateLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UpdateLogScalarFieldEnum | Prisma.UpdateLogScalarFieldEnum[]
}

/**
 * DnsRecord without action
 */
export type DnsRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DnsRecord
   */
  select?: Prisma.DnsRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DnsRecord
   */
  omit?: Prisma.DnsRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DnsRecordInclude<ExtArgs> | null
}
