
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HealthCheckLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model HealthCheckLog
 * 
 */
export type HealthCheckLogModel = runtime.Types.Result.DefaultSelection<Prisma.$HealthCheckLogPayload>

export type AggregateHealthCheckLog = {
  _count: HealthCheckLogCountAggregateOutputType | null
  _avg: HealthCheckLogAvgAggregateOutputType | null
  _sum: HealthCheckLogSumAggregateOutputType | null
  _min: HealthCheckLogMinAggregateOutputType | null
  _max: HealthCheckLogMaxAggregateOutputType | null
}

export type HealthCheckLogAvgAggregateOutputType = {
  id: number | null
  healthCheckId: number | null
  responseTime: number | null
}

export type HealthCheckLogSumAggregateOutputType = {
  id: number | null
  healthCheckId: number | null
  responseTime: number | null
}

export type HealthCheckLogMinAggregateOutputType = {
  id: number | null
  healthCheckId: number | null
  status: string | null
  responseTime: number | null
  message: string | null
  createdAt: Date | null
}

export type HealthCheckLogMaxAggregateOutputType = {
  id: number | null
  healthCheckId: number | null
  status: string | null
  responseTime: number | null
  message: string | null
  createdAt: Date | null
}

export type HealthCheckLogCountAggregateOutputType = {
  id: number
  healthCheckId: number
  status: number
  responseTime: number
  message: number
  createdAt: number
  _all: number
}


export type HealthCheckLogAvgAggregateInputType = {
  id?: true
  healthCheckId?: true
  responseTime?: true
}

export type HealthCheckLogSumAggregateInputType = {
  id?: true
  healthCheckId?: true
  responseTime?: true
}

export type HealthCheckLogMinAggregateInputType = {
  id?: true
  healthCheckId?: true
  status?: true
  responseTime?: true
  message?: true
  createdAt?: true
}

export type HealthCheckLogMaxAggregateInputType = {
  id?: true
  healthCheckId?: true
  status?: true
  responseTime?: true
  message?: true
  createdAt?: true
}

export type HealthCheckLogCountAggregateInputType = {
  id?: true
  healthCheckId?: true
  status?: true
  responseTime?: true
  message?: true
  createdAt?: true
  _all?: true
}

export type HealthCheckLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HealthCheckLog to aggregate.
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthCheckLogs to fetch.
   */
  orderBy?: Prisma.HealthCheckLogOrderByWithRelationInput | Prisma.HealthCheckLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HealthCheckLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthCheckLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthCheckLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HealthCheckLogs
  **/
  _count?: true | HealthCheckLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HealthCheckLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HealthCheckLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HealthCheckLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HealthCheckLogMaxAggregateInputType
}

export type GetHealthCheckLogAggregateType<T extends HealthCheckLogAggregateArgs> = {
      [P in keyof T & keyof AggregateHealthCheckLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHealthCheckLog[P]>
    : Prisma.GetScalarType<T[P], AggregateHealthCheckLog[P]>
}




export type HealthCheckLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HealthCheckLogWhereInput
  orderBy?: Prisma.HealthCheckLogOrderByWithAggregationInput | Prisma.HealthCheckLogOrderByWithAggregationInput[]
  by: Prisma.HealthCheckLogScalarFieldEnum[] | Prisma.HealthCheckLogScalarFieldEnum
  having?: Prisma.HealthCheckLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HealthCheckLogCountAggregateInputType | true
  _avg?: HealthCheckLogAvgAggregateInputType
  _sum?: HealthCheckLogSumAggregateInputType
  _min?: HealthCheckLogMinAggregateInputType
  _max?: HealthCheckLogMaxAggregateInputType
}

export type HealthCheckLogGroupByOutputType = {
  id: number
  healthCheckId: number
  status: string
  responseTime: number | null
  message: string | null
  createdAt: Date
  _count: HealthCheckLogCountAggregateOutputType | null
  _avg: HealthCheckLogAvgAggregateOutputType | null
  _sum: HealthCheckLogSumAggregateOutputType | null
  _min: HealthCheckLogMinAggregateOutputType | null
  _max: HealthCheckLogMaxAggregateOutputType | null
}

type GetHealthCheckLogGroupByPayload<T extends HealthCheckLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HealthCheckLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HealthCheckLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HealthCheckLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HealthCheckLogGroupByOutputType[P]>
      }
    >
  >



export type HealthCheckLogWhereInput = {
  AND?: Prisma.HealthCheckLogWhereInput | Prisma.HealthCheckLogWhereInput[]
  OR?: Prisma.HealthCheckLogWhereInput[]
  NOT?: Prisma.HealthCheckLogWhereInput | Prisma.HealthCheckLogWhereInput[]
  id?: Prisma.IntFilter<"HealthCheckLog"> | number
  healthCheckId?: Prisma.IntFilter<"HealthCheckLog"> | number
  status?: Prisma.StringFilter<"HealthCheckLog"> | string
  responseTime?: Prisma.IntNullableFilter<"HealthCheckLog"> | number | null
  message?: Prisma.StringNullableFilter<"HealthCheckLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HealthCheckLog"> | Date | string
  healthCheck?: Prisma.XOR<Prisma.HealthCheckScalarRelationFilter, Prisma.HealthCheckWhereInput>
}

export type HealthCheckLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  healthCheck?: Prisma.HealthCheckOrderByWithRelationInput
}

export type HealthCheckLogWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HealthCheckLogWhereInput | Prisma.HealthCheckLogWhereInput[]
  OR?: Prisma.HealthCheckLogWhereInput[]
  NOT?: Prisma.HealthCheckLogWhereInput | Prisma.HealthCheckLogWhereInput[]
  healthCheckId?: Prisma.IntFilter<"HealthCheckLog"> | number
  status?: Prisma.StringFilter<"HealthCheckLog"> | string
  responseTime?: Prisma.IntNullableFilter<"HealthCheckLog"> | number | null
  message?: Prisma.StringNullableFilter<"HealthCheckLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HealthCheckLog"> | Date | string
  healthCheck?: Prisma.XOR<Prisma.HealthCheckScalarRelationFilter, Prisma.HealthCheckWhereInput>
}, "id">

export type HealthCheckLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.HealthCheckLogCountOrderByAggregateInput
  _avg?: Prisma.HealthCheckLogAvgOrderByAggregateInput
  _max?: Prisma.HealthCheckLogMaxOrderByAggregateInput
  _min?: Prisma.HealthCheckLogMinOrderByAggregateInput
  _sum?: Prisma.HealthCheckLogSumOrderByAggregateInput
}

export type HealthCheckLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.HealthCheckLogScalarWhereWithAggregatesInput | Prisma.HealthCheckLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.HealthCheckLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HealthCheckLogScalarWhereWithAggregatesInput | Prisma.HealthCheckLogScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"HealthCheckLog"> | number
  healthCheckId?: Prisma.IntWithAggregatesFilter<"HealthCheckLog"> | number
  status?: Prisma.StringWithAggregatesFilter<"HealthCheckLog"> | string
  responseTime?: Prisma.IntNullableWithAggregatesFilter<"HealthCheckLog"> | number | null
  message?: Prisma.StringNullableWithAggregatesFilter<"HealthCheckLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HealthCheckLog"> | Date | string
}

export type HealthCheckLogCreateInput = {
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
  healthCheck: Prisma.HealthCheckCreateNestedOneWithoutLogsInput
}

export type HealthCheckLogUncheckedCreateInput = {
  id?: number
  healthCheckId: number
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
}

export type HealthCheckLogUpdateInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  healthCheck?: Prisma.HealthCheckUpdateOneRequiredWithoutLogsNestedInput
}

export type HealthCheckLogUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  healthCheckId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckLogCreateManyInput = {
  id?: number
  healthCheckId: number
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
}

export type HealthCheckLogUpdateManyMutationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckLogUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  healthCheckId?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckLogListRelationFilter = {
  every?: Prisma.HealthCheckLogWhereInput
  some?: Prisma.HealthCheckLogWhereInput
  none?: Prisma.HealthCheckLogWhereInput
}

export type HealthCheckLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HealthCheckLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
}

export type HealthCheckLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  healthCheckId?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
}

export type HealthCheckLogCreateNestedManyWithoutHealthCheckInput = {
  create?: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput> | Prisma.HealthCheckLogCreateWithoutHealthCheckInput[] | Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput[]
  connectOrCreate?: Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput | Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput[]
  createMany?: Prisma.HealthCheckLogCreateManyHealthCheckInputEnvelope
  connect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
}

export type HealthCheckLogUncheckedCreateNestedManyWithoutHealthCheckInput = {
  create?: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput> | Prisma.HealthCheckLogCreateWithoutHealthCheckInput[] | Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput[]
  connectOrCreate?: Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput | Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput[]
  createMany?: Prisma.HealthCheckLogCreateManyHealthCheckInputEnvelope
  connect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
}

export type HealthCheckLogUpdateManyWithoutHealthCheckNestedInput = {
  create?: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput> | Prisma.HealthCheckLogCreateWithoutHealthCheckInput[] | Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput[]
  connectOrCreate?: Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput | Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput[]
  upsert?: Prisma.HealthCheckLogUpsertWithWhereUniqueWithoutHealthCheckInput | Prisma.HealthCheckLogUpsertWithWhereUniqueWithoutHealthCheckInput[]
  createMany?: Prisma.HealthCheckLogCreateManyHealthCheckInputEnvelope
  set?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  disconnect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  delete?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  connect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  update?: Prisma.HealthCheckLogUpdateWithWhereUniqueWithoutHealthCheckInput | Prisma.HealthCheckLogUpdateWithWhereUniqueWithoutHealthCheckInput[]
  updateMany?: Prisma.HealthCheckLogUpdateManyWithWhereWithoutHealthCheckInput | Prisma.HealthCheckLogUpdateManyWithWhereWithoutHealthCheckInput[]
  deleteMany?: Prisma.HealthCheckLogScalarWhereInput | Prisma.HealthCheckLogScalarWhereInput[]
}

export type HealthCheckLogUncheckedUpdateManyWithoutHealthCheckNestedInput = {
  create?: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput> | Prisma.HealthCheckLogCreateWithoutHealthCheckInput[] | Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput[]
  connectOrCreate?: Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput | Prisma.HealthCheckLogCreateOrConnectWithoutHealthCheckInput[]
  upsert?: Prisma.HealthCheckLogUpsertWithWhereUniqueWithoutHealthCheckInput | Prisma.HealthCheckLogUpsertWithWhereUniqueWithoutHealthCheckInput[]
  createMany?: Prisma.HealthCheckLogCreateManyHealthCheckInputEnvelope
  set?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  disconnect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  delete?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  connect?: Prisma.HealthCheckLogWhereUniqueInput | Prisma.HealthCheckLogWhereUniqueInput[]
  update?: Prisma.HealthCheckLogUpdateWithWhereUniqueWithoutHealthCheckInput | Prisma.HealthCheckLogUpdateWithWhereUniqueWithoutHealthCheckInput[]
  updateMany?: Prisma.HealthCheckLogUpdateManyWithWhereWithoutHealthCheckInput | Prisma.HealthCheckLogUpdateManyWithWhereWithoutHealthCheckInput[]
  deleteMany?: Prisma.HealthCheckLogScalarWhereInput | Prisma.HealthCheckLogScalarWhereInput[]
}

export type HealthCheckLogCreateWithoutHealthCheckInput = {
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
}

export type HealthCheckLogUncheckedCreateWithoutHealthCheckInput = {
  id?: number
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
}

export type HealthCheckLogCreateOrConnectWithoutHealthCheckInput = {
  where: Prisma.HealthCheckLogWhereUniqueInput
  create: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput>
}

export type HealthCheckLogCreateManyHealthCheckInputEnvelope = {
  data: Prisma.HealthCheckLogCreateManyHealthCheckInput | Prisma.HealthCheckLogCreateManyHealthCheckInput[]
}

export type HealthCheckLogUpsertWithWhereUniqueWithoutHealthCheckInput = {
  where: Prisma.HealthCheckLogWhereUniqueInput
  update: Prisma.XOR<Prisma.HealthCheckLogUpdateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedUpdateWithoutHealthCheckInput>
  create: Prisma.XOR<Prisma.HealthCheckLogCreateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedCreateWithoutHealthCheckInput>
}

export type HealthCheckLogUpdateWithWhereUniqueWithoutHealthCheckInput = {
  where: Prisma.HealthCheckLogWhereUniqueInput
  data: Prisma.XOR<Prisma.HealthCheckLogUpdateWithoutHealthCheckInput, Prisma.HealthCheckLogUncheckedUpdateWithoutHealthCheckInput>
}

export type HealthCheckLogUpdateManyWithWhereWithoutHealthCheckInput = {
  where: Prisma.HealthCheckLogScalarWhereInput
  data: Prisma.XOR<Prisma.HealthCheckLogUpdateManyMutationInput, Prisma.HealthCheckLogUncheckedUpdateManyWithoutHealthCheckInput>
}

export type HealthCheckLogScalarWhereInput = {
  AND?: Prisma.HealthCheckLogScalarWhereInput | Prisma.HealthCheckLogScalarWhereInput[]
  OR?: Prisma.HealthCheckLogScalarWhereInput[]
  NOT?: Prisma.HealthCheckLogScalarWhereInput | Prisma.HealthCheckLogScalarWhereInput[]
  id?: Prisma.IntFilter<"HealthCheckLog"> | number
  healthCheckId?: Prisma.IntFilter<"HealthCheckLog"> | number
  status?: Prisma.StringFilter<"HealthCheckLog"> | string
  responseTime?: Prisma.IntNullableFilter<"HealthCheckLog"> | number | null
  message?: Prisma.StringNullableFilter<"HealthCheckLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HealthCheckLog"> | Date | string
}

export type HealthCheckLogCreateManyHealthCheckInput = {
  id?: number
  status: string
  responseTime?: number | null
  message?: string | null
  createdAt?: Date | string
}

export type HealthCheckLogUpdateWithoutHealthCheckInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckLogUncheckedUpdateWithoutHealthCheckInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckLogUncheckedUpdateManyWithoutHealthCheckInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  responseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type HealthCheckLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  healthCheckId?: boolean
  status?: boolean
  responseTime?: boolean
  message?: boolean
  createdAt?: boolean
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}, ExtArgs["result"]["healthCheckLog"]>

export type HealthCheckLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  healthCheckId?: boolean
  status?: boolean
  responseTime?: boolean
  message?: boolean
  createdAt?: boolean
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}, ExtArgs["result"]["healthCheckLog"]>

export type HealthCheckLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  healthCheckId?: boolean
  status?: boolean
  responseTime?: boolean
  message?: boolean
  createdAt?: boolean
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}, ExtArgs["result"]["healthCheckLog"]>

export type HealthCheckLogSelectScalar = {
  id?: boolean
  healthCheckId?: boolean
  status?: boolean
  responseTime?: boolean
  message?: boolean
  createdAt?: boolean
}

export type HealthCheckLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "healthCheckId" | "status" | "responseTime" | "message" | "createdAt", ExtArgs["result"]["healthCheckLog"]>
export type HealthCheckLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}
export type HealthCheckLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}
export type HealthCheckLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  healthCheck?: boolean | Prisma.HealthCheckDefaultArgs<ExtArgs>
}

export type $HealthCheckLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HealthCheckLog"
  objects: {
    healthCheck: Prisma.$HealthCheckPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    healthCheckId: number
    status: string
    responseTime: number | null
    message: string | null
    createdAt: Date
  }, ExtArgs["result"]["healthCheckLog"]>
  composites: {}
}

export type HealthCheckLogGetPayload<S extends boolean | null | undefined | HealthCheckLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload, S>

export type HealthCheckLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HealthCheckLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HealthCheckLogCountAggregateInputType | true
  }

export interface HealthCheckLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HealthCheckLog'], meta: { name: 'HealthCheckLog' } }
  /**
   * Find zero or one HealthCheckLog that matches the filter.
   * @param {HealthCheckLogFindUniqueArgs} args - Arguments to find a HealthCheckLog
   * @example
   * // Get one HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HealthCheckLogFindUniqueArgs>(args: Prisma.SelectSubset<T, HealthCheckLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HealthCheckLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HealthCheckLogFindUniqueOrThrowArgs} args - Arguments to find a HealthCheckLog
   * @example
   * // Get one HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HealthCheckLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HealthCheckLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HealthCheckLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogFindFirstArgs} args - Arguments to find a HealthCheckLog
   * @example
   * // Get one HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HealthCheckLogFindFirstArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HealthCheckLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogFindFirstOrThrowArgs} args - Arguments to find a HealthCheckLog
   * @example
   * // Get one HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HealthCheckLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HealthCheckLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HealthCheckLogs
   * const healthCheckLogs = await prisma.healthCheckLog.findMany()
   * 
   * // Get first 10 HealthCheckLogs
   * const healthCheckLogs = await prisma.healthCheckLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const healthCheckLogWithIdOnly = await prisma.healthCheckLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HealthCheckLogFindManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HealthCheckLog.
   * @param {HealthCheckLogCreateArgs} args - Arguments to create a HealthCheckLog.
   * @example
   * // Create one HealthCheckLog
   * const HealthCheckLog = await prisma.healthCheckLog.create({
   *   data: {
   *     // ... data to create a HealthCheckLog
   *   }
   * })
   * 
   */
  create<T extends HealthCheckLogCreateArgs>(args: Prisma.SelectSubset<T, HealthCheckLogCreateArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HealthCheckLogs.
   * @param {HealthCheckLogCreateManyArgs} args - Arguments to create many HealthCheckLogs.
   * @example
   * // Create many HealthCheckLogs
   * const healthCheckLog = await prisma.healthCheckLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HealthCheckLogCreateManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HealthCheckLogs and returns the data saved in the database.
   * @param {HealthCheckLogCreateManyAndReturnArgs} args - Arguments to create many HealthCheckLogs.
   * @example
   * // Create many HealthCheckLogs
   * const healthCheckLog = await prisma.healthCheckLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HealthCheckLogs and only return the `id`
   * const healthCheckLogWithIdOnly = await prisma.healthCheckLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HealthCheckLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HealthCheckLog.
   * @param {HealthCheckLogDeleteArgs} args - Arguments to delete one HealthCheckLog.
   * @example
   * // Delete one HealthCheckLog
   * const HealthCheckLog = await prisma.healthCheckLog.delete({
   *   where: {
   *     // ... filter to delete one HealthCheckLog
   *   }
   * })
   * 
   */
  delete<T extends HealthCheckLogDeleteArgs>(args: Prisma.SelectSubset<T, HealthCheckLogDeleteArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HealthCheckLog.
   * @param {HealthCheckLogUpdateArgs} args - Arguments to update one HealthCheckLog.
   * @example
   * // Update one HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HealthCheckLogUpdateArgs>(args: Prisma.SelectSubset<T, HealthCheckLogUpdateArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HealthCheckLogs.
   * @param {HealthCheckLogDeleteManyArgs} args - Arguments to filter HealthCheckLogs to delete.
   * @example
   * // Delete a few HealthCheckLogs
   * const { count } = await prisma.healthCheckLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HealthCheckLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HealthCheckLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HealthCheckLogs
   * const healthCheckLog = await prisma.healthCheckLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HealthCheckLogUpdateManyArgs>(args: Prisma.SelectSubset<T, HealthCheckLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HealthCheckLogs and returns the data updated in the database.
   * @param {HealthCheckLogUpdateManyAndReturnArgs} args - Arguments to update many HealthCheckLogs.
   * @example
   * // Update many HealthCheckLogs
   * const healthCheckLog = await prisma.healthCheckLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HealthCheckLogs and only return the `id`
   * const healthCheckLogWithIdOnly = await prisma.healthCheckLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HealthCheckLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HealthCheckLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HealthCheckLog.
   * @param {HealthCheckLogUpsertArgs} args - Arguments to update or create a HealthCheckLog.
   * @example
   * // Update or create a HealthCheckLog
   * const healthCheckLog = await prisma.healthCheckLog.upsert({
   *   create: {
   *     // ... data to create a HealthCheckLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HealthCheckLog we want to update
   *   }
   * })
   */
  upsert<T extends HealthCheckLogUpsertArgs>(args: Prisma.SelectSubset<T, HealthCheckLogUpsertArgs<ExtArgs>>): Prisma.Prisma__HealthCheckLogClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HealthCheckLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogCountArgs} args - Arguments to filter HealthCheckLogs to count.
   * @example
   * // Count the number of HealthCheckLogs
   * const count = await prisma.healthCheckLog.count({
   *   where: {
   *     // ... the filter for the HealthCheckLogs we want to count
   *   }
   * })
  **/
  count<T extends HealthCheckLogCountArgs>(
    args?: Prisma.Subset<T, HealthCheckLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HealthCheckLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HealthCheckLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HealthCheckLogAggregateArgs>(args: Prisma.Subset<T, HealthCheckLogAggregateArgs>): Prisma.PrismaPromise<GetHealthCheckLogAggregateType<T>>

  /**
   * Group by HealthCheckLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HealthCheckLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HealthCheckLogGroupByArgs['orderBy'] }
      : { orderBy?: HealthCheckLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HealthCheckLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHealthCheckLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HealthCheckLog model
 */
readonly fields: HealthCheckLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HealthCheckLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HealthCheckLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  healthCheck<T extends Prisma.HealthCheckDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HealthCheckDefaultArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HealthCheckLog model
 */
export interface HealthCheckLogFieldRefs {
  readonly id: Prisma.FieldRef<"HealthCheckLog", 'Int'>
  readonly healthCheckId: Prisma.FieldRef<"HealthCheckLog", 'Int'>
  readonly status: Prisma.FieldRef<"HealthCheckLog", 'String'>
  readonly responseTime: Prisma.FieldRef<"HealthCheckLog", 'Int'>
  readonly message: Prisma.FieldRef<"HealthCheckLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"HealthCheckLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * HealthCheckLog findUnique
 */
export type HealthCheckLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheckLog to fetch.
   */
  where: Prisma.HealthCheckLogWhereUniqueInput
}

/**
 * HealthCheckLog findUniqueOrThrow
 */
export type HealthCheckLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheckLog to fetch.
   */
  where: Prisma.HealthCheckLogWhereUniqueInput
}

/**
 * HealthCheckLog findFirst
 */
export type HealthCheckLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheckLog to fetch.
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthCheckLogs to fetch.
   */
  orderBy?: Prisma.HealthCheckLogOrderByWithRelationInput | Prisma.HealthCheckLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HealthCheckLogs.
   */
  cursor?: Prisma.HealthCheckLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthCheckLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthCheckLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HealthCheckLogs.
   */
  distinct?: Prisma.HealthCheckLogScalarFieldEnum | Prisma.HealthCheckLogScalarFieldEnum[]
}

/**
 * HealthCheckLog findFirstOrThrow
 */
export type HealthCheckLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheckLog to fetch.
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthCheckLogs to fetch.
   */
  orderBy?: Prisma.HealthCheckLogOrderByWithRelationInput | Prisma.HealthCheckLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HealthCheckLogs.
   */
  cursor?: Prisma.HealthCheckLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthCheckLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthCheckLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HealthCheckLogs.
   */
  distinct?: Prisma.HealthCheckLogScalarFieldEnum | Prisma.HealthCheckLogScalarFieldEnum[]
}

/**
 * HealthCheckLog findMany
 */
export type HealthCheckLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheckLogs to fetch.
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthCheckLogs to fetch.
   */
  orderBy?: Prisma.HealthCheckLogOrderByWithRelationInput | Prisma.HealthCheckLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HealthCheckLogs.
   */
  cursor?: Prisma.HealthCheckLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthCheckLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthCheckLogs.
   */
  skip?: number
  distinct?: Prisma.HealthCheckLogScalarFieldEnum | Prisma.HealthCheckLogScalarFieldEnum[]
}

/**
 * HealthCheckLog create
 */
export type HealthCheckLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * The data needed to create a HealthCheckLog.
   */
  data: Prisma.XOR<Prisma.HealthCheckLogCreateInput, Prisma.HealthCheckLogUncheckedCreateInput>
}

/**
 * HealthCheckLog createMany
 */
export type HealthCheckLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HealthCheckLogs.
   */
  data: Prisma.HealthCheckLogCreateManyInput | Prisma.HealthCheckLogCreateManyInput[]
}

/**
 * HealthCheckLog createManyAndReturn
 */
export type HealthCheckLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * The data used to create many HealthCheckLogs.
   */
  data: Prisma.HealthCheckLogCreateManyInput | Prisma.HealthCheckLogCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * HealthCheckLog update
 */
export type HealthCheckLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * The data needed to update a HealthCheckLog.
   */
  data: Prisma.XOR<Prisma.HealthCheckLogUpdateInput, Prisma.HealthCheckLogUncheckedUpdateInput>
  /**
   * Choose, which HealthCheckLog to update.
   */
  where: Prisma.HealthCheckLogWhereUniqueInput
}

/**
 * HealthCheckLog updateMany
 */
export type HealthCheckLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HealthCheckLogs.
   */
  data: Prisma.XOR<Prisma.HealthCheckLogUpdateManyMutationInput, Prisma.HealthCheckLogUncheckedUpdateManyInput>
  /**
   * Filter which HealthCheckLogs to update
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * Limit how many HealthCheckLogs to update.
   */
  limit?: number
}

/**
 * HealthCheckLog updateManyAndReturn
 */
export type HealthCheckLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * The data used to update HealthCheckLogs.
   */
  data: Prisma.XOR<Prisma.HealthCheckLogUpdateManyMutationInput, Prisma.HealthCheckLogUncheckedUpdateManyInput>
  /**
   * Filter which HealthCheckLogs to update
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * Limit how many HealthCheckLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * HealthCheckLog upsert
 */
export type HealthCheckLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * The filter to search for the HealthCheckLog to update in case it exists.
   */
  where: Prisma.HealthCheckLogWhereUniqueInput
  /**
   * In case the HealthCheckLog found by the `where` argument doesn't exist, create a new HealthCheckLog with this data.
   */
  create: Prisma.XOR<Prisma.HealthCheckLogCreateInput, Prisma.HealthCheckLogUncheckedCreateInput>
  /**
   * In case the HealthCheckLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HealthCheckLogUpdateInput, Prisma.HealthCheckLogUncheckedUpdateInput>
}

/**
 * HealthCheckLog delete
 */
export type HealthCheckLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  /**
   * Filter which HealthCheckLog to delete.
   */
  where: Prisma.HealthCheckLogWhereUniqueInput
}

/**
 * HealthCheckLog deleteMany
 */
export type HealthCheckLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HealthCheckLogs to delete
   */
  where?: Prisma.HealthCheckLogWhereInput
  /**
   * Limit how many HealthCheckLogs to delete.
   */
  limit?: number
}

/**
 * HealthCheckLog without action
 */
export type HealthCheckLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
}
