
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HealthCheck` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model HealthCheck
 * 
 */
export type HealthCheckModel = runtime.Types.Result.DefaultSelection<Prisma.$HealthCheckPayload>

export type AggregateHealthCheck = {
  _count: HealthCheckCountAggregateOutputType | null
  _avg: HealthCheckAvgAggregateOutputType | null
  _sum: HealthCheckSumAggregateOutputType | null
  _min: HealthCheckMinAggregateOutputType | null
  _max: HealthCheckMaxAggregateOutputType | null
}

export type HealthCheckAvgAggregateOutputType = {
  id: number | null
  interval: number | null
}

export type HealthCheckSumAggregateOutputType = {
  id: number | null
  interval: number | null
}

export type HealthCheckMinAggregateOutputType = {
  id: number | null
  name: string | null
  type: string | null
  target: string | null
  interval: number | null
  lastStatus: string | null
  lastCheckAt: Date | null
  isEnabled: boolean | null
  createdAt: Date | null
}

export type HealthCheckMaxAggregateOutputType = {
  id: number | null
  name: string | null
  type: string | null
  target: string | null
  interval: number | null
  lastStatus: string | null
  lastCheckAt: Date | null
  isEnabled: boolean | null
  createdAt: Date | null
}

export type HealthCheckCountAggregateOutputType = {
  id: number
  name: number
  type: number
  target: number
  interval: number
  lastStatus: number
  lastCheckAt: number
  isEnabled: number
  createdAt: number
  _all: number
}


export type HealthCheckAvgAggregateInputType = {
  id?: true
  interval?: true
}

export type HealthCheckSumAggregateInputType = {
  id?: true
  interval?: true
}

export type HealthCheckMinAggregateInputType = {
  id?: true
  name?: true
  type?: true
  target?: true
  interval?: true
  lastStatus?: true
  lastCheckAt?: true
  isEnabled?: true
  createdAt?: true
}

export type HealthCheckMaxAggregateInputType = {
  id?: true
  name?: true
  type?: true
  target?: true
  interval?: true
  lastStatus?: true
  lastCheckAt?: true
  isEnabled?: true
  createdAt?: true
}

export type HealthCheckCountAggregateInputType = {
  id?: true
  name?: true
  type?: true
  target?: true
  interval?: true
  lastStatus?: true
  lastCheckAt?: true
  isEnabled?: true
  createdAt?: true
  _all?: true
}

export type HealthCheckAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HealthCheck to aggregate.
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthChecks to fetch.
   */
  orderBy?: Prisma.HealthCheckOrderByWithRelationInput | Prisma.HealthCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HealthCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HealthChecks
  **/
  _count?: true | HealthCheckCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HealthCheckAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HealthCheckSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HealthCheckMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HealthCheckMaxAggregateInputType
}

export type GetHealthCheckAggregateType<T extends HealthCheckAggregateArgs> = {
      [P in keyof T & keyof AggregateHealthCheck]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHealthCheck[P]>
    : Prisma.GetScalarType<T[P], AggregateHealthCheck[P]>
}




export type HealthCheckGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HealthCheckWhereInput
  orderBy?: Prisma.HealthCheckOrderByWithAggregationInput | Prisma.HealthCheckOrderByWithAggregationInput[]
  by: Prisma.HealthCheckScalarFieldEnum[] | Prisma.HealthCheckScalarFieldEnum
  having?: Prisma.HealthCheckScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HealthCheckCountAggregateInputType | true
  _avg?: HealthCheckAvgAggregateInputType
  _sum?: HealthCheckSumAggregateInputType
  _min?: HealthCheckMinAggregateInputType
  _max?: HealthCheckMaxAggregateInputType
}

export type HealthCheckGroupByOutputType = {
  id: number
  name: string
  type: string
  target: string
  interval: number
  lastStatus: string | null
  lastCheckAt: Date | null
  isEnabled: boolean
  createdAt: Date
  _count: HealthCheckCountAggregateOutputType | null
  _avg: HealthCheckAvgAggregateOutputType | null
  _sum: HealthCheckSumAggregateOutputType | null
  _min: HealthCheckMinAggregateOutputType | null
  _max: HealthCheckMaxAggregateOutputType | null
}

type GetHealthCheckGroupByPayload<T extends HealthCheckGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HealthCheckGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HealthCheckGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HealthCheckGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HealthCheckGroupByOutputType[P]>
      }
    >
  >



export type HealthCheckWhereInput = {
  AND?: Prisma.HealthCheckWhereInput | Prisma.HealthCheckWhereInput[]
  OR?: Prisma.HealthCheckWhereInput[]
  NOT?: Prisma.HealthCheckWhereInput | Prisma.HealthCheckWhereInput[]
  id?: Prisma.IntFilter<"HealthCheck"> | number
  name?: Prisma.StringFilter<"HealthCheck"> | string
  type?: Prisma.StringFilter<"HealthCheck"> | string
  target?: Prisma.StringFilter<"HealthCheck"> | string
  interval?: Prisma.IntFilter<"HealthCheck"> | number
  lastStatus?: Prisma.StringNullableFilter<"HealthCheck"> | string | null
  lastCheckAt?: Prisma.DateTimeNullableFilter<"HealthCheck"> | Date | string | null
  isEnabled?: Prisma.BoolFilter<"HealthCheck"> | boolean
  createdAt?: Prisma.DateTimeFilter<"HealthCheck"> | Date | string
  logs?: Prisma.HealthCheckLogListRelationFilter
}

export type HealthCheckOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  target?: Prisma.SortOrder
  interval?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  lastCheckAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  logs?: Prisma.HealthCheckLogOrderByRelationAggregateInput
}

export type HealthCheckWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HealthCheckWhereInput | Prisma.HealthCheckWhereInput[]
  OR?: Prisma.HealthCheckWhereInput[]
  NOT?: Prisma.HealthCheckWhereInput | Prisma.HealthCheckWhereInput[]
  name?: Prisma.StringFilter<"HealthCheck"> | string
  type?: Prisma.StringFilter<"HealthCheck"> | string
  target?: Prisma.StringFilter<"HealthCheck"> | string
  interval?: Prisma.IntFilter<"HealthCheck"> | number
  lastStatus?: Prisma.StringNullableFilter<"HealthCheck"> | string | null
  lastCheckAt?: Prisma.DateTimeNullableFilter<"HealthCheck"> | Date | string | null
  isEnabled?: Prisma.BoolFilter<"HealthCheck"> | boolean
  createdAt?: Prisma.DateTimeFilter<"HealthCheck"> | Date | string
  logs?: Prisma.HealthCheckLogListRelationFilter
}, "id">

export type HealthCheckOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  target?: Prisma.SortOrder
  interval?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  lastCheckAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.HealthCheckCountOrderByAggregateInput
  _avg?: Prisma.HealthCheckAvgOrderByAggregateInput
  _max?: Prisma.HealthCheckMaxOrderByAggregateInput
  _min?: Prisma.HealthCheckMinOrderByAggregateInput
  _sum?: Prisma.HealthCheckSumOrderByAggregateInput
}

export type HealthCheckScalarWhereWithAggregatesInput = {
  AND?: Prisma.HealthCheckScalarWhereWithAggregatesInput | Prisma.HealthCheckScalarWhereWithAggregatesInput[]
  OR?: Prisma.HealthCheckScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HealthCheckScalarWhereWithAggregatesInput | Prisma.HealthCheckScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"HealthCheck"> | number
  name?: Prisma.StringWithAggregatesFilter<"HealthCheck"> | string
  type?: Prisma.StringWithAggregatesFilter<"HealthCheck"> | string
  target?: Prisma.StringWithAggregatesFilter<"HealthCheck"> | string
  interval?: Prisma.IntWithAggregatesFilter<"HealthCheck"> | number
  lastStatus?: Prisma.StringNullableWithAggregatesFilter<"HealthCheck"> | string | null
  lastCheckAt?: Prisma.DateTimeNullableWithAggregatesFilter<"HealthCheck"> | Date | string | null
  isEnabled?: Prisma.BoolWithAggregatesFilter<"HealthCheck"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HealthCheck"> | Date | string
}

export type HealthCheckCreateInput = {
  name: string
  type: string
  target: string
  interval?: number
  lastStatus?: string | null
  lastCheckAt?: Date | string | null
  isEnabled?: boolean
  createdAt?: Date | string
  logs?: Prisma.HealthCheckLogCreateNestedManyWithoutHealthCheckInput
}

export type HealthCheckUncheckedCreateInput = {
  id?: number
  name: string
  type: string
  target: string
  interval?: number
  lastStatus?: string | null
  lastCheckAt?: Date | string | null
  isEnabled?: boolean
  createdAt?: Date | string
  logs?: Prisma.HealthCheckLogUncheckedCreateNestedManyWithoutHealthCheckInput
}

export type HealthCheckUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.HealthCheckLogUpdateManyWithoutHealthCheckNestedInput
}

export type HealthCheckUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  logs?: Prisma.HealthCheckLogUncheckedUpdateManyWithoutHealthCheckNestedInput
}

export type HealthCheckCreateManyInput = {
  id?: number
  name: string
  type: string
  target: string
  interval?: number
  lastStatus?: string | null
  lastCheckAt?: Date | string | null
  isEnabled?: boolean
  createdAt?: Date | string
}

export type HealthCheckUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  target?: Prisma.SortOrder
  interval?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastCheckAt?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  interval?: Prisma.SortOrder
}

export type HealthCheckMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  target?: Prisma.SortOrder
  interval?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastCheckAt?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  target?: Prisma.SortOrder
  interval?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastCheckAt?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HealthCheckSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  interval?: Prisma.SortOrder
}

export type HealthCheckScalarRelationFilter = {
  is?: Prisma.HealthCheckWhereInput
  isNot?: Prisma.HealthCheckWhereInput
}

export type HealthCheckCreateNestedOneWithoutLogsInput = {
  create?: Prisma.XOR<Prisma.HealthCheckCreateWithoutLogsInput, Prisma.HealthCheckUncheckedCreateWithoutLogsInput>
  connectOrCreate?: Prisma.HealthCheckCreateOrConnectWithoutLogsInput
  connect?: Prisma.HealthCheckWhereUniqueInput
}

export type HealthCheckUpdateOneRequiredWithoutLogsNestedInput = {
  create?: Prisma.XOR<Prisma.HealthCheckCreateWithoutLogsInput, Prisma.HealthCheckUncheckedCreateWithoutLogsInput>
  connectOrCreate?: Prisma.HealthCheckCreateOrConnectWithoutLogsInput
  upsert?: Prisma.HealthCheckUpsertWithoutLogsInput
  connect?: Prisma.HealthCheckWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HealthCheckUpdateToOneWithWhereWithoutLogsInput, Prisma.HealthCheckUpdateWithoutLogsInput>, Prisma.HealthCheckUncheckedUpdateWithoutLogsInput>
}

export type HealthCheckCreateWithoutLogsInput = {
  name: string
  type: string
  target: string
  interval?: number
  lastStatus?: string | null
  lastCheckAt?: Date | string | null
  isEnabled?: boolean
  createdAt?: Date | string
}

export type HealthCheckUncheckedCreateWithoutLogsInput = {
  id?: number
  name: string
  type: string
  target: string
  interval?: number
  lastStatus?: string | null
  lastCheckAt?: Date | string | null
  isEnabled?: boolean
  createdAt?: Date | string
}

export type HealthCheckCreateOrConnectWithoutLogsInput = {
  where: Prisma.HealthCheckWhereUniqueInput
  create: Prisma.XOR<Prisma.HealthCheckCreateWithoutLogsInput, Prisma.HealthCheckUncheckedCreateWithoutLogsInput>
}

export type HealthCheckUpsertWithoutLogsInput = {
  update: Prisma.XOR<Prisma.HealthCheckUpdateWithoutLogsInput, Prisma.HealthCheckUncheckedUpdateWithoutLogsInput>
  create: Prisma.XOR<Prisma.HealthCheckCreateWithoutLogsInput, Prisma.HealthCheckUncheckedCreateWithoutLogsInput>
  where?: Prisma.HealthCheckWhereInput
}

export type HealthCheckUpdateToOneWithWhereWithoutLogsInput = {
  where?: Prisma.HealthCheckWhereInput
  data: Prisma.XOR<Prisma.HealthCheckUpdateWithoutLogsInput, Prisma.HealthCheckUncheckedUpdateWithoutLogsInput>
}

export type HealthCheckUpdateWithoutLogsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HealthCheckUncheckedUpdateWithoutLogsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  target?: Prisma.StringFieldUpdateOperationsInput | string
  interval?: Prisma.IntFieldUpdateOperationsInput | number
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastCheckAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type HealthCheckCountOutputType
 */

export type HealthCheckCountOutputType = {
  logs: number
}

export type HealthCheckCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  logs?: boolean | HealthCheckCountOutputTypeCountLogsArgs
}

/**
 * HealthCheckCountOutputType without action
 */
export type HealthCheckCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckCountOutputType
   */
  select?: Prisma.HealthCheckCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HealthCheckCountOutputType without action
 */
export type HealthCheckCountOutputTypeCountLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HealthCheckLogWhereInput
}


export type HealthCheckSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  target?: boolean
  interval?: boolean
  lastStatus?: boolean
  lastCheckAt?: boolean
  isEnabled?: boolean
  createdAt?: boolean
  logs?: boolean | Prisma.HealthCheck$logsArgs<ExtArgs>
  _count?: boolean | Prisma.HealthCheckCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["healthCheck"]>

export type HealthCheckSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  target?: boolean
  interval?: boolean
  lastStatus?: boolean
  lastCheckAt?: boolean
  isEnabled?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["healthCheck"]>

export type HealthCheckSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  type?: boolean
  target?: boolean
  interval?: boolean
  lastStatus?: boolean
  lastCheckAt?: boolean
  isEnabled?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["healthCheck"]>

export type HealthCheckSelectScalar = {
  id?: boolean
  name?: boolean
  type?: boolean
  target?: boolean
  interval?: boolean
  lastStatus?: boolean
  lastCheckAt?: boolean
  isEnabled?: boolean
  createdAt?: boolean
}

export type HealthCheckOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "type" | "target" | "interval" | "lastStatus" | "lastCheckAt" | "isEnabled" | "createdAt", ExtArgs["result"]["healthCheck"]>
export type HealthCheckInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  logs?: boolean | Prisma.HealthCheck$logsArgs<ExtArgs>
  _count?: boolean | Prisma.HealthCheckCountOutputTypeDefaultArgs<ExtArgs>
}
export type HealthCheckIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type HealthCheckIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $HealthCheckPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HealthCheck"
  objects: {
    logs: Prisma.$HealthCheckLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    type: string
    target: string
    interval: number
    lastStatus: string | null
    lastCheckAt: Date | null
    isEnabled: boolean
    createdAt: Date
  }, ExtArgs["result"]["healthCheck"]>
  composites: {}
}

export type HealthCheckGetPayload<S extends boolean | null | undefined | HealthCheckDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload, S>

export type HealthCheckCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HealthCheckFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HealthCheckCountAggregateInputType | true
  }

export interface HealthCheckDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HealthCheck'], meta: { name: 'HealthCheck' } }
  /**
   * Find zero or one HealthCheck that matches the filter.
   * @param {HealthCheckFindUniqueArgs} args - Arguments to find a HealthCheck
   * @example
   * // Get one HealthCheck
   * const healthCheck = await prisma.healthCheck.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HealthCheckFindUniqueArgs>(args: Prisma.SelectSubset<T, HealthCheckFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HealthCheck that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HealthCheckFindUniqueOrThrowArgs} args - Arguments to find a HealthCheck
   * @example
   * // Get one HealthCheck
   * const healthCheck = await prisma.healthCheck.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HealthCheckFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HealthCheckFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HealthCheck that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckFindFirstArgs} args - Arguments to find a HealthCheck
   * @example
   * // Get one HealthCheck
   * const healthCheck = await prisma.healthCheck.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HealthCheckFindFirstArgs>(args?: Prisma.SelectSubset<T, HealthCheckFindFirstArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HealthCheck that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckFindFirstOrThrowArgs} args - Arguments to find a HealthCheck
   * @example
   * // Get one HealthCheck
   * const healthCheck = await prisma.healthCheck.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HealthCheckFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HealthCheckFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HealthChecks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HealthChecks
   * const healthChecks = await prisma.healthCheck.findMany()
   * 
   * // Get first 10 HealthChecks
   * const healthChecks = await prisma.healthCheck.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const healthCheckWithIdOnly = await prisma.healthCheck.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HealthCheckFindManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HealthCheck.
   * @param {HealthCheckCreateArgs} args - Arguments to create a HealthCheck.
   * @example
   * // Create one HealthCheck
   * const HealthCheck = await prisma.healthCheck.create({
   *   data: {
   *     // ... data to create a HealthCheck
   *   }
   * })
   * 
   */
  create<T extends HealthCheckCreateArgs>(args: Prisma.SelectSubset<T, HealthCheckCreateArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HealthChecks.
   * @param {HealthCheckCreateManyArgs} args - Arguments to create many HealthChecks.
   * @example
   * // Create many HealthChecks
   * const healthCheck = await prisma.healthCheck.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HealthCheckCreateManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HealthChecks and returns the data saved in the database.
   * @param {HealthCheckCreateManyAndReturnArgs} args - Arguments to create many HealthChecks.
   * @example
   * // Create many HealthChecks
   * const healthCheck = await prisma.healthCheck.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HealthChecks and only return the `id`
   * const healthCheckWithIdOnly = await prisma.healthCheck.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HealthCheckCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HealthCheckCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HealthCheck.
   * @param {HealthCheckDeleteArgs} args - Arguments to delete one HealthCheck.
   * @example
   * // Delete one HealthCheck
   * const HealthCheck = await prisma.healthCheck.delete({
   *   where: {
   *     // ... filter to delete one HealthCheck
   *   }
   * })
   * 
   */
  delete<T extends HealthCheckDeleteArgs>(args: Prisma.SelectSubset<T, HealthCheckDeleteArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HealthCheck.
   * @param {HealthCheckUpdateArgs} args - Arguments to update one HealthCheck.
   * @example
   * // Update one HealthCheck
   * const healthCheck = await prisma.healthCheck.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HealthCheckUpdateArgs>(args: Prisma.SelectSubset<T, HealthCheckUpdateArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HealthChecks.
   * @param {HealthCheckDeleteManyArgs} args - Arguments to filter HealthChecks to delete.
   * @example
   * // Delete a few HealthChecks
   * const { count } = await prisma.healthCheck.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HealthCheckDeleteManyArgs>(args?: Prisma.SelectSubset<T, HealthCheckDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HealthChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HealthChecks
   * const healthCheck = await prisma.healthCheck.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HealthCheckUpdateManyArgs>(args: Prisma.SelectSubset<T, HealthCheckUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HealthChecks and returns the data updated in the database.
   * @param {HealthCheckUpdateManyAndReturnArgs} args - Arguments to update many HealthChecks.
   * @example
   * // Update many HealthChecks
   * const healthCheck = await prisma.healthCheck.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HealthChecks and only return the `id`
   * const healthCheckWithIdOnly = await prisma.healthCheck.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HealthCheckUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HealthCheckUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HealthCheck.
   * @param {HealthCheckUpsertArgs} args - Arguments to update or create a HealthCheck.
   * @example
   * // Update or create a HealthCheck
   * const healthCheck = await prisma.healthCheck.upsert({
   *   create: {
   *     // ... data to create a HealthCheck
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HealthCheck we want to update
   *   }
   * })
   */
  upsert<T extends HealthCheckUpsertArgs>(args: Prisma.SelectSubset<T, HealthCheckUpsertArgs<ExtArgs>>): Prisma.Prisma__HealthCheckClient<runtime.Types.Result.GetResult<Prisma.$HealthCheckPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HealthChecks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckCountArgs} args - Arguments to filter HealthChecks to count.
   * @example
   * // Count the number of HealthChecks
   * const count = await prisma.healthCheck.count({
   *   where: {
   *     // ... the filter for the HealthChecks we want to count
   *   }
   * })
  **/
  count<T extends HealthCheckCountArgs>(
    args?: Prisma.Subset<T, HealthCheckCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HealthCheckCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HealthCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HealthCheckAggregateArgs>(args: Prisma.Subset<T, HealthCheckAggregateArgs>): Prisma.PrismaPromise<GetHealthCheckAggregateType<T>>

  /**
   * Group by HealthCheck.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HealthCheckGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HealthCheckGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HealthCheckGroupByArgs['orderBy'] }
      : { orderBy?: HealthCheckGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HealthCheckGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHealthCheckGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HealthCheck model
 */
readonly fields: HealthCheckFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HealthCheck.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HealthCheckClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  logs<T extends Prisma.HealthCheck$logsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HealthCheck$logsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HealthCheckLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HealthCheck model
 */
export interface HealthCheckFieldRefs {
  readonly id: Prisma.FieldRef<"HealthCheck", 'Int'>
  readonly name: Prisma.FieldRef<"HealthCheck", 'String'>
  readonly type: Prisma.FieldRef<"HealthCheck", 'String'>
  readonly target: Prisma.FieldRef<"HealthCheck", 'String'>
  readonly interval: Prisma.FieldRef<"HealthCheck", 'Int'>
  readonly lastStatus: Prisma.FieldRef<"HealthCheck", 'String'>
  readonly lastCheckAt: Prisma.FieldRef<"HealthCheck", 'DateTime'>
  readonly isEnabled: Prisma.FieldRef<"HealthCheck", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"HealthCheck", 'DateTime'>
}
    

// Custom InputTypes
/**
 * HealthCheck findUnique
 */
export type HealthCheckFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheck to fetch.
   */
  where: Prisma.HealthCheckWhereUniqueInput
}

/**
 * HealthCheck findUniqueOrThrow
 */
export type HealthCheckFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheck to fetch.
   */
  where: Prisma.HealthCheckWhereUniqueInput
}

/**
 * HealthCheck findFirst
 */
export type HealthCheckFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheck to fetch.
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthChecks to fetch.
   */
  orderBy?: Prisma.HealthCheckOrderByWithRelationInput | Prisma.HealthCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HealthChecks.
   */
  cursor?: Prisma.HealthCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HealthChecks.
   */
  distinct?: Prisma.HealthCheckScalarFieldEnum | Prisma.HealthCheckScalarFieldEnum[]
}

/**
 * HealthCheck findFirstOrThrow
 */
export type HealthCheckFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter, which HealthCheck to fetch.
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthChecks to fetch.
   */
  orderBy?: Prisma.HealthCheckOrderByWithRelationInput | Prisma.HealthCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HealthChecks.
   */
  cursor?: Prisma.HealthCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthChecks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HealthChecks.
   */
  distinct?: Prisma.HealthCheckScalarFieldEnum | Prisma.HealthCheckScalarFieldEnum[]
}

/**
 * HealthCheck findMany
 */
export type HealthCheckFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter, which HealthChecks to fetch.
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HealthChecks to fetch.
   */
  orderBy?: Prisma.HealthCheckOrderByWithRelationInput | Prisma.HealthCheckOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HealthChecks.
   */
  cursor?: Prisma.HealthCheckWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HealthChecks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HealthChecks.
   */
  skip?: number
  distinct?: Prisma.HealthCheckScalarFieldEnum | Prisma.HealthCheckScalarFieldEnum[]
}

/**
 * HealthCheck create
 */
export type HealthCheckCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * The data needed to create a HealthCheck.
   */
  data: Prisma.XOR<Prisma.HealthCheckCreateInput, Prisma.HealthCheckUncheckedCreateInput>
}

/**
 * HealthCheck createMany
 */
export type HealthCheckCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HealthChecks.
   */
  data: Prisma.HealthCheckCreateManyInput | Prisma.HealthCheckCreateManyInput[]
}

/**
 * HealthCheck createManyAndReturn
 */
export type HealthCheckCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * The data used to create many HealthChecks.
   */
  data: Prisma.HealthCheckCreateManyInput | Prisma.HealthCheckCreateManyInput[]
}

/**
 * HealthCheck update
 */
export type HealthCheckUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * The data needed to update a HealthCheck.
   */
  data: Prisma.XOR<Prisma.HealthCheckUpdateInput, Prisma.HealthCheckUncheckedUpdateInput>
  /**
   * Choose, which HealthCheck to update.
   */
  where: Prisma.HealthCheckWhereUniqueInput
}

/**
 * HealthCheck updateMany
 */
export type HealthCheckUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HealthChecks.
   */
  data: Prisma.XOR<Prisma.HealthCheckUpdateManyMutationInput, Prisma.HealthCheckUncheckedUpdateManyInput>
  /**
   * Filter which HealthChecks to update
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * Limit how many HealthChecks to update.
   */
  limit?: number
}

/**
 * HealthCheck updateManyAndReturn
 */
export type HealthCheckUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * The data used to update HealthChecks.
   */
  data: Prisma.XOR<Prisma.HealthCheckUpdateManyMutationInput, Prisma.HealthCheckUncheckedUpdateManyInput>
  /**
   * Filter which HealthChecks to update
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * Limit how many HealthChecks to update.
   */
  limit?: number
}

/**
 * HealthCheck upsert
 */
export type HealthCheckUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * The filter to search for the HealthCheck to update in case it exists.
   */
  where: Prisma.HealthCheckWhereUniqueInput
  /**
   * In case the HealthCheck found by the `where` argument doesn't exist, create a new HealthCheck with this data.
   */
  create: Prisma.XOR<Prisma.HealthCheckCreateInput, Prisma.HealthCheckUncheckedCreateInput>
  /**
   * In case the HealthCheck was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HealthCheckUpdateInput, Prisma.HealthCheckUncheckedUpdateInput>
}

/**
 * HealthCheck delete
 */
export type HealthCheckDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
  /**
   * Filter which HealthCheck to delete.
   */
  where: Prisma.HealthCheckWhereUniqueInput
}

/**
 * HealthCheck deleteMany
 */
export type HealthCheckDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HealthChecks to delete
   */
  where?: Prisma.HealthCheckWhereInput
  /**
   * Limit how many HealthChecks to delete.
   */
  limit?: number
}

/**
 * HealthCheck.logs
 */
export type HealthCheck$logsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheckLog
   */
  select?: Prisma.HealthCheckLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheckLog
   */
  omit?: Prisma.HealthCheckLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckLogInclude<ExtArgs> | null
  where?: Prisma.HealthCheckLogWhereInput
  orderBy?: Prisma.HealthCheckLogOrderByWithRelationInput | Prisma.HealthCheckLogOrderByWithRelationInput[]
  cursor?: Prisma.HealthCheckLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HealthCheckLogScalarFieldEnum | Prisma.HealthCheckLogScalarFieldEnum[]
}

/**
 * HealthCheck without action
 */
export type HealthCheckDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HealthCheck
   */
  select?: Prisma.HealthCheckSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HealthCheck
   */
  omit?: Prisma.HealthCheckOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HealthCheckInclude<ExtArgs> | null
}
