
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UpdateLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UpdateLog
 * 
 */
export type UpdateLogModel = runtime.Types.Result.DefaultSelection<Prisma.$UpdateLogPayload>

export type AggregateUpdateLog = {
  _count: UpdateLogCountAggregateOutputType | null
  _avg: UpdateLogAvgAggregateOutputType | null
  _sum: UpdateLogSumAggregateOutputType | null
  _min: UpdateLogMinAggregateOutputType | null
  _max: UpdateLogMaxAggregateOutputType | null
}

export type UpdateLogAvgAggregateOutputType = {
  id: number | null
  recordId: number | null
}

export type UpdateLogSumAggregateOutputType = {
  id: number | null
  recordId: number | null
}

export type UpdateLogMinAggregateOutputType = {
  id: number | null
  oldIp: string | null
  newIp: string | null
  status: string | null
  recordId: number | null
  message: string | null
  createdAt: Date | null
}

export type UpdateLogMaxAggregateOutputType = {
  id: number | null
  oldIp: string | null
  newIp: string | null
  status: string | null
  recordId: number | null
  message: string | null
  createdAt: Date | null
}

export type UpdateLogCountAggregateOutputType = {
  id: number
  oldIp: number
  newIp: number
  status: number
  recordId: number
  message: number
  createdAt: number
  _all: number
}


export type UpdateLogAvgAggregateInputType = {
  id?: true
  recordId?: true
}

export type UpdateLogSumAggregateInputType = {
  id?: true
  recordId?: true
}

export type UpdateLogMinAggregateInputType = {
  id?: true
  oldIp?: true
  newIp?: true
  status?: true
  recordId?: true
  message?: true
  createdAt?: true
}

export type UpdateLogMaxAggregateInputType = {
  id?: true
  oldIp?: true
  newIp?: true
  status?: true
  recordId?: true
  message?: true
  createdAt?: true
}

export type UpdateLogCountAggregateInputType = {
  id?: true
  oldIp?: true
  newIp?: true
  status?: true
  recordId?: true
  message?: true
  createdAt?: true
  _all?: true
}

export type UpdateLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UpdateLog to aggregate.
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UpdateLogs to fetch.
   */
  orderBy?: Prisma.UpdateLogOrderByWithRelationInput | Prisma.UpdateLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UpdateLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UpdateLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UpdateLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UpdateLogs
  **/
  _count?: true | UpdateLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UpdateLogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UpdateLogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UpdateLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UpdateLogMaxAggregateInputType
}

export type GetUpdateLogAggregateType<T extends UpdateLogAggregateArgs> = {
      [P in keyof T & keyof AggregateUpdateLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUpdateLog[P]>
    : Prisma.GetScalarType<T[P], AggregateUpdateLog[P]>
}




export type UpdateLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UpdateLogWhereInput
  orderBy?: Prisma.UpdateLogOrderByWithAggregationInput | Prisma.UpdateLogOrderByWithAggregationInput[]
  by: Prisma.UpdateLogScalarFieldEnum[] | Prisma.UpdateLogScalarFieldEnum
  having?: Prisma.UpdateLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UpdateLogCountAggregateInputType | true
  _avg?: UpdateLogAvgAggregateInputType
  _sum?: UpdateLogSumAggregateInputType
  _min?: UpdateLogMinAggregateInputType
  _max?: UpdateLogMaxAggregateInputType
}

export type UpdateLogGroupByOutputType = {
  id: number
  oldIp: string | null
  newIp: string
  status: string
  recordId: number
  message: string | null
  createdAt: Date
  _count: UpdateLogCountAggregateOutputType | null
  _avg: UpdateLogAvgAggregateOutputType | null
  _sum: UpdateLogSumAggregateOutputType | null
  _min: UpdateLogMinAggregateOutputType | null
  _max: UpdateLogMaxAggregateOutputType | null
}

type GetUpdateLogGroupByPayload<T extends UpdateLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UpdateLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UpdateLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UpdateLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UpdateLogGroupByOutputType[P]>
      }
    >
  >



export type UpdateLogWhereInput = {
  AND?: Prisma.UpdateLogWhereInput | Prisma.UpdateLogWhereInput[]
  OR?: Prisma.UpdateLogWhereInput[]
  NOT?: Prisma.UpdateLogWhereInput | Prisma.UpdateLogWhereInput[]
  id?: Prisma.IntFilter<"UpdateLog"> | number
  oldIp?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  newIp?: Prisma.StringFilter<"UpdateLog"> | string
  status?: Prisma.StringFilter<"UpdateLog"> | string
  recordId?: Prisma.IntFilter<"UpdateLog"> | number
  message?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UpdateLog"> | Date | string
  record?: Prisma.XOR<Prisma.DnsRecordScalarRelationFilter, Prisma.DnsRecordWhereInput>
}

export type UpdateLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  oldIp?: Prisma.SortOrderInput | Prisma.SortOrder
  newIp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  record?: Prisma.DnsRecordOrderByWithRelationInput
}

export type UpdateLogWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.UpdateLogWhereInput | Prisma.UpdateLogWhereInput[]
  OR?: Prisma.UpdateLogWhereInput[]
  NOT?: Prisma.UpdateLogWhereInput | Prisma.UpdateLogWhereInput[]
  oldIp?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  newIp?: Prisma.StringFilter<"UpdateLog"> | string
  status?: Prisma.StringFilter<"UpdateLog"> | string
  recordId?: Prisma.IntFilter<"UpdateLog"> | number
  message?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UpdateLog"> | Date | string
  record?: Prisma.XOR<Prisma.DnsRecordScalarRelationFilter, Prisma.DnsRecordWhereInput>
}, "id">

export type UpdateLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  oldIp?: Prisma.SortOrderInput | Prisma.SortOrder
  newIp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UpdateLogCountOrderByAggregateInput
  _avg?: Prisma.UpdateLogAvgOrderByAggregateInput
  _max?: Prisma.UpdateLogMaxOrderByAggregateInput
  _min?: Prisma.UpdateLogMinOrderByAggregateInput
  _sum?: Prisma.UpdateLogSumOrderByAggregateInput
}

export type UpdateLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.UpdateLogScalarWhereWithAggregatesInput | Prisma.UpdateLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.UpdateLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UpdateLogScalarWhereWithAggregatesInput | Prisma.UpdateLogScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UpdateLog"> | number
  oldIp?: Prisma.StringNullableWithAggregatesFilter<"UpdateLog"> | string | null
  newIp?: Prisma.StringWithAggregatesFilter<"UpdateLog"> | string
  status?: Prisma.StringWithAggregatesFilter<"UpdateLog"> | string
  recordId?: Prisma.IntWithAggregatesFilter<"UpdateLog"> | number
  message?: Prisma.StringNullableWithAggregatesFilter<"UpdateLog"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UpdateLog"> | Date | string
}

export type UpdateLogCreateInput = {
  oldIp?: string | null
  newIp: string
  status: string
  message?: string | null
  createdAt?: Date | string
  record: Prisma.DnsRecordCreateNestedOneWithoutUpdateLogsInput
}

export type UpdateLogUncheckedCreateInput = {
  id?: number
  oldIp?: string | null
  newIp: string
  status: string
  recordId: number
  message?: string | null
  createdAt?: Date | string
}

export type UpdateLogUpdateInput = {
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  record?: Prisma.DnsRecordUpdateOneRequiredWithoutUpdateLogsNestedInput
}

export type UpdateLogUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UpdateLogCreateManyInput = {
  id?: number
  oldIp?: string | null
  newIp: string
  status: string
  recordId: number
  message?: string | null
  createdAt?: Date | string
}

export type UpdateLogUpdateManyMutationInput = {
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UpdateLogUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UpdateLogListRelationFilter = {
  every?: Prisma.UpdateLogWhereInput
  some?: Prisma.UpdateLogWhereInput
  none?: Prisma.UpdateLogWhereInput
}

export type UpdateLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UpdateLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oldIp?: Prisma.SortOrder
  newIp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UpdateLogAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type UpdateLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oldIp?: Prisma.SortOrder
  newIp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UpdateLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oldIp?: Prisma.SortOrder
  newIp?: Prisma.SortOrder
  status?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  message?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UpdateLogSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type UpdateLogCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput> | Prisma.UpdateLogCreateWithoutRecordInput[] | Prisma.UpdateLogUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.UpdateLogCreateOrConnectWithoutRecordInput | Prisma.UpdateLogCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.UpdateLogCreateManyRecordInputEnvelope
  connect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
}

export type UpdateLogUncheckedCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput> | Prisma.UpdateLogCreateWithoutRecordInput[] | Prisma.UpdateLogUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.UpdateLogCreateOrConnectWithoutRecordInput | Prisma.UpdateLogCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.UpdateLogCreateManyRecordInputEnvelope
  connect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
}

export type UpdateLogUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput> | Prisma.UpdateLogCreateWithoutRecordInput[] | Prisma.UpdateLogUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.UpdateLogCreateOrConnectWithoutRecordInput | Prisma.UpdateLogCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.UpdateLogUpsertWithWhereUniqueWithoutRecordInput | Prisma.UpdateLogUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.UpdateLogCreateManyRecordInputEnvelope
  set?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  disconnect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  delete?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  connect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  update?: Prisma.UpdateLogUpdateWithWhereUniqueWithoutRecordInput | Prisma.UpdateLogUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.UpdateLogUpdateManyWithWhereWithoutRecordInput | Prisma.UpdateLogUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.UpdateLogScalarWhereInput | Prisma.UpdateLogScalarWhereInput[]
}

export type UpdateLogUncheckedUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput> | Prisma.UpdateLogCreateWithoutRecordInput[] | Prisma.UpdateLogUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.UpdateLogCreateOrConnectWithoutRecordInput | Prisma.UpdateLogCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.UpdateLogUpsertWithWhereUniqueWithoutRecordInput | Prisma.UpdateLogUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.UpdateLogCreateManyRecordInputEnvelope
  set?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  disconnect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  delete?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  connect?: Prisma.UpdateLogWhereUniqueInput | Prisma.UpdateLogWhereUniqueInput[]
  update?: Prisma.UpdateLogUpdateWithWhereUniqueWithoutRecordInput | Prisma.UpdateLogUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.UpdateLogUpdateManyWithWhereWithoutRecordInput | Prisma.UpdateLogUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.UpdateLogScalarWhereInput | Prisma.UpdateLogScalarWhereInput[]
}

export type UpdateLogCreateWithoutRecordInput = {
  oldIp?: string | null
  newIp: string
  status: string
  message?: string | null
  createdAt?: Date | string
}

export type UpdateLogUncheckedCreateWithoutRecordInput = {
  id?: number
  oldIp?: string | null
  newIp: string
  status: string
  message?: string | null
  createdAt?: Date | string
}

export type UpdateLogCreateOrConnectWithoutRecordInput = {
  where: Prisma.UpdateLogWhereUniqueInput
  create: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput>
}

export type UpdateLogCreateManyRecordInputEnvelope = {
  data: Prisma.UpdateLogCreateManyRecordInput | Prisma.UpdateLogCreateManyRecordInput[]
}

export type UpdateLogUpsertWithWhereUniqueWithoutRecordInput = {
  where: Prisma.UpdateLogWhereUniqueInput
  update: Prisma.XOR<Prisma.UpdateLogUpdateWithoutRecordInput, Prisma.UpdateLogUncheckedUpdateWithoutRecordInput>
  create: Prisma.XOR<Prisma.UpdateLogCreateWithoutRecordInput, Prisma.UpdateLogUncheckedCreateWithoutRecordInput>
}

export type UpdateLogUpdateWithWhereUniqueWithoutRecordInput = {
  where: Prisma.UpdateLogWhereUniqueInput
  data: Prisma.XOR<Prisma.UpdateLogUpdateWithoutRecordInput, Prisma.UpdateLogUncheckedUpdateWithoutRecordInput>
}

export type UpdateLogUpdateManyWithWhereWithoutRecordInput = {
  where: Prisma.UpdateLogScalarWhereInput
  data: Prisma.XOR<Prisma.UpdateLogUpdateManyMutationInput, Prisma.UpdateLogUncheckedUpdateManyWithoutRecordInput>
}

export type UpdateLogScalarWhereInput = {
  AND?: Prisma.UpdateLogScalarWhereInput | Prisma.UpdateLogScalarWhereInput[]
  OR?: Prisma.UpdateLogScalarWhereInput[]
  NOT?: Prisma.UpdateLogScalarWhereInput | Prisma.UpdateLogScalarWhereInput[]
  id?: Prisma.IntFilter<"UpdateLog"> | number
  oldIp?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  newIp?: Prisma.StringFilter<"UpdateLog"> | string
  status?: Prisma.StringFilter<"UpdateLog"> | string
  recordId?: Prisma.IntFilter<"UpdateLog"> | number
  message?: Prisma.StringNullableFilter<"UpdateLog"> | string | null
  createdAt?: Prisma.DateTimeFilter<"UpdateLog"> | Date | string
}

export type UpdateLogCreateManyRecordInput = {
  id?: number
  oldIp?: string | null
  newIp: string
  status: string
  message?: string | null
  createdAt?: Date | string
}

export type UpdateLogUpdateWithoutRecordInput = {
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UpdateLogUncheckedUpdateWithoutRecordInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UpdateLogUncheckedUpdateManyWithoutRecordInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  oldIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newIp?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UpdateLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  oldIp?: boolean
  newIp?: boolean
  status?: boolean
  recordId?: boolean
  message?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["updateLog"]>

export type UpdateLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  oldIp?: boolean
  newIp?: boolean
  status?: boolean
  recordId?: boolean
  message?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["updateLog"]>

export type UpdateLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  oldIp?: boolean
  newIp?: boolean
  status?: boolean
  recordId?: boolean
  message?: boolean
  createdAt?: boolean
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["updateLog"]>

export type UpdateLogSelectScalar = {
  id?: boolean
  oldIp?: boolean
  newIp?: boolean
  status?: boolean
  recordId?: boolean
  message?: boolean
  createdAt?: boolean
}

export type UpdateLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "oldIp" | "newIp" | "status" | "recordId" | "message" | "createdAt", ExtArgs["result"]["updateLog"]>
export type UpdateLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}
export type UpdateLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}
export type UpdateLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.DnsRecordDefaultArgs<ExtArgs>
}

export type $UpdateLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UpdateLog"
  objects: {
    record: Prisma.$DnsRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    oldIp: string | null
    newIp: string
    status: string
    recordId: number
    message: string | null
    createdAt: Date
  }, ExtArgs["result"]["updateLog"]>
  composites: {}
}

export type UpdateLogGetPayload<S extends boolean | null | undefined | UpdateLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload, S>

export type UpdateLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UpdateLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UpdateLogCountAggregateInputType | true
  }

export interface UpdateLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UpdateLog'], meta: { name: 'UpdateLog' } }
  /**
   * Find zero or one UpdateLog that matches the filter.
   * @param {UpdateLogFindUniqueArgs} args - Arguments to find a UpdateLog
   * @example
   * // Get one UpdateLog
   * const updateLog = await prisma.updateLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UpdateLogFindUniqueArgs>(args: Prisma.SelectSubset<T, UpdateLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UpdateLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UpdateLogFindUniqueOrThrowArgs} args - Arguments to find a UpdateLog
   * @example
   * // Get one UpdateLog
   * const updateLog = await prisma.updateLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UpdateLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UpdateLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UpdateLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogFindFirstArgs} args - Arguments to find a UpdateLog
   * @example
   * // Get one UpdateLog
   * const updateLog = await prisma.updateLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UpdateLogFindFirstArgs>(args?: Prisma.SelectSubset<T, UpdateLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UpdateLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogFindFirstOrThrowArgs} args - Arguments to find a UpdateLog
   * @example
   * // Get one UpdateLog
   * const updateLog = await prisma.updateLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UpdateLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UpdateLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UpdateLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UpdateLogs
   * const updateLogs = await prisma.updateLog.findMany()
   * 
   * // Get first 10 UpdateLogs
   * const updateLogs = await prisma.updateLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const updateLogWithIdOnly = await prisma.updateLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UpdateLogFindManyArgs>(args?: Prisma.SelectSubset<T, UpdateLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UpdateLog.
   * @param {UpdateLogCreateArgs} args - Arguments to create a UpdateLog.
   * @example
   * // Create one UpdateLog
   * const UpdateLog = await prisma.updateLog.create({
   *   data: {
   *     // ... data to create a UpdateLog
   *   }
   * })
   * 
   */
  create<T extends UpdateLogCreateArgs>(args: Prisma.SelectSubset<T, UpdateLogCreateArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UpdateLogs.
   * @param {UpdateLogCreateManyArgs} args - Arguments to create many UpdateLogs.
   * @example
   * // Create many UpdateLogs
   * const updateLog = await prisma.updateLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UpdateLogCreateManyArgs>(args?: Prisma.SelectSubset<T, UpdateLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UpdateLogs and returns the data saved in the database.
   * @param {UpdateLogCreateManyAndReturnArgs} args - Arguments to create many UpdateLogs.
   * @example
   * // Create many UpdateLogs
   * const updateLog = await prisma.updateLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UpdateLogs and only return the `id`
   * const updateLogWithIdOnly = await prisma.updateLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UpdateLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UpdateLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UpdateLog.
   * @param {UpdateLogDeleteArgs} args - Arguments to delete one UpdateLog.
   * @example
   * // Delete one UpdateLog
   * const UpdateLog = await prisma.updateLog.delete({
   *   where: {
   *     // ... filter to delete one UpdateLog
   *   }
   * })
   * 
   */
  delete<T extends UpdateLogDeleteArgs>(args: Prisma.SelectSubset<T, UpdateLogDeleteArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UpdateLog.
   * @param {UpdateLogUpdateArgs} args - Arguments to update one UpdateLog.
   * @example
   * // Update one UpdateLog
   * const updateLog = await prisma.updateLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UpdateLogUpdateArgs>(args: Prisma.SelectSubset<T, UpdateLogUpdateArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UpdateLogs.
   * @param {UpdateLogDeleteManyArgs} args - Arguments to filter UpdateLogs to delete.
   * @example
   * // Delete a few UpdateLogs
   * const { count } = await prisma.updateLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UpdateLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, UpdateLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UpdateLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UpdateLogs
   * const updateLog = await prisma.updateLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UpdateLogUpdateManyArgs>(args: Prisma.SelectSubset<T, UpdateLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UpdateLogs and returns the data updated in the database.
   * @param {UpdateLogUpdateManyAndReturnArgs} args - Arguments to update many UpdateLogs.
   * @example
   * // Update many UpdateLogs
   * const updateLog = await prisma.updateLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UpdateLogs and only return the `id`
   * const updateLogWithIdOnly = await prisma.updateLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UpdateLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UpdateLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UpdateLog.
   * @param {UpdateLogUpsertArgs} args - Arguments to update or create a UpdateLog.
   * @example
   * // Update or create a UpdateLog
   * const updateLog = await prisma.updateLog.upsert({
   *   create: {
   *     // ... data to create a UpdateLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UpdateLog we want to update
   *   }
   * })
   */
  upsert<T extends UpdateLogUpsertArgs>(args: Prisma.SelectSubset<T, UpdateLogUpsertArgs<ExtArgs>>): Prisma.Prisma__UpdateLogClient<runtime.Types.Result.GetResult<Prisma.$UpdateLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UpdateLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogCountArgs} args - Arguments to filter UpdateLogs to count.
   * @example
   * // Count the number of UpdateLogs
   * const count = await prisma.updateLog.count({
   *   where: {
   *     // ... the filter for the UpdateLogs we want to count
   *   }
   * })
  **/
  count<T extends UpdateLogCountArgs>(
    args?: Prisma.Subset<T, UpdateLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UpdateLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UpdateLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UpdateLogAggregateArgs>(args: Prisma.Subset<T, UpdateLogAggregateArgs>): Prisma.PrismaPromise<GetUpdateLogAggregateType<T>>

  /**
   * Group by UpdateLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UpdateLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UpdateLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UpdateLogGroupByArgs['orderBy'] }
      : { orderBy?: UpdateLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UpdateLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUpdateLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UpdateLog model
 */
readonly fields: UpdateLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UpdateLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UpdateLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  record<T extends Prisma.DnsRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DnsRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__DnsRecordClient<runtime.Types.Result.GetResult<Prisma.$DnsRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UpdateLog model
 */
export interface UpdateLogFieldRefs {
  readonly id: Prisma.FieldRef<"UpdateLog", 'Int'>
  readonly oldIp: Prisma.FieldRef<"UpdateLog", 'String'>
  readonly newIp: Prisma.FieldRef<"UpdateLog", 'String'>
  readonly status: Prisma.FieldRef<"UpdateLog", 'String'>
  readonly recordId: Prisma.FieldRef<"UpdateLog", 'Int'>
  readonly message: Prisma.FieldRef<"UpdateLog", 'String'>
  readonly createdAt: Prisma.FieldRef<"UpdateLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UpdateLog findUnique
 */
export type UpdateLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter, which UpdateLog to fetch.
   */
  where: Prisma.UpdateLogWhereUniqueInput
}

/**
 * UpdateLog findUniqueOrThrow
 */
export type UpdateLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter, which UpdateLog to fetch.
   */
  where: Prisma.UpdateLogWhereUniqueInput
}

/**
 * UpdateLog findFirst
 */
export type UpdateLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter, which UpdateLog to fetch.
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UpdateLogs to fetch.
   */
  orderBy?: Prisma.UpdateLogOrderByWithRelationInput | Prisma.UpdateLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UpdateLogs.
   */
  cursor?: Prisma.UpdateLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UpdateLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UpdateLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UpdateLogs.
   */
  distinct?: Prisma.UpdateLogScalarFieldEnum | Prisma.UpdateLogScalarFieldEnum[]
}

/**
 * UpdateLog findFirstOrThrow
 */
export type UpdateLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter, which UpdateLog to fetch.
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UpdateLogs to fetch.
   */
  orderBy?: Prisma.UpdateLogOrderByWithRelationInput | Prisma.UpdateLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UpdateLogs.
   */
  cursor?: Prisma.UpdateLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UpdateLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UpdateLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UpdateLogs.
   */
  distinct?: Prisma.UpdateLogScalarFieldEnum | Prisma.UpdateLogScalarFieldEnum[]
}

/**
 * UpdateLog findMany
 */
export type UpdateLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter, which UpdateLogs to fetch.
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UpdateLogs to fetch.
   */
  orderBy?: Prisma.UpdateLogOrderByWithRelationInput | Prisma.UpdateLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UpdateLogs.
   */
  cursor?: Prisma.UpdateLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UpdateLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UpdateLogs.
   */
  skip?: number
  distinct?: Prisma.UpdateLogScalarFieldEnum | Prisma.UpdateLogScalarFieldEnum[]
}

/**
 * UpdateLog create
 */
export type UpdateLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * The data needed to create a UpdateLog.
   */
  data: Prisma.XOR<Prisma.UpdateLogCreateInput, Prisma.UpdateLogUncheckedCreateInput>
}

/**
 * UpdateLog createMany
 */
export type UpdateLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UpdateLogs.
   */
  data: Prisma.UpdateLogCreateManyInput | Prisma.UpdateLogCreateManyInput[]
}

/**
 * UpdateLog createManyAndReturn
 */
export type UpdateLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * The data used to create many UpdateLogs.
   */
  data: Prisma.UpdateLogCreateManyInput | Prisma.UpdateLogCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UpdateLog update
 */
export type UpdateLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * The data needed to update a UpdateLog.
   */
  data: Prisma.XOR<Prisma.UpdateLogUpdateInput, Prisma.UpdateLogUncheckedUpdateInput>
  /**
   * Choose, which UpdateLog to update.
   */
  where: Prisma.UpdateLogWhereUniqueInput
}

/**
 * UpdateLog updateMany
 */
export type UpdateLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UpdateLogs.
   */
  data: Prisma.XOR<Prisma.UpdateLogUpdateManyMutationInput, Prisma.UpdateLogUncheckedUpdateManyInput>
  /**
   * Filter which UpdateLogs to update
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * Limit how many UpdateLogs to update.
   */
  limit?: number
}

/**
 * UpdateLog updateManyAndReturn
 */
export type UpdateLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * The data used to update UpdateLogs.
   */
  data: Prisma.XOR<Prisma.UpdateLogUpdateManyMutationInput, Prisma.UpdateLogUncheckedUpdateManyInput>
  /**
   * Filter which UpdateLogs to update
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * Limit how many UpdateLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UpdateLog upsert
 */
export type UpdateLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * The filter to search for the UpdateLog to update in case it exists.
   */
  where: Prisma.UpdateLogWhereUniqueInput
  /**
   * In case the UpdateLog found by the `where` argument doesn't exist, create a new UpdateLog with this data.
   */
  create: Prisma.XOR<Prisma.UpdateLogCreateInput, Prisma.UpdateLogUncheckedCreateInput>
  /**
   * In case the UpdateLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UpdateLogUpdateInput, Prisma.UpdateLogUncheckedUpdateInput>
}

/**
 * UpdateLog delete
 */
export type UpdateLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
  /**
   * Filter which UpdateLog to delete.
   */
  where: Prisma.UpdateLogWhereUniqueInput
}

/**
 * UpdateLog deleteMany
 */
export type UpdateLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UpdateLogs to delete
   */
  where?: Prisma.UpdateLogWhereInput
  /**
   * Limit how many UpdateLogs to delete.
   */
  limit?: number
}

/**
 * UpdateLog without action
 */
export type UpdateLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UpdateLog
   */
  select?: Prisma.UpdateLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UpdateLog
   */
  omit?: Prisma.UpdateLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UpdateLogInclude<ExtArgs> | null
}
