
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model CloudflareAccount
 * 
 */
export type CloudflareAccount = Prisma.CloudflareAccountModel
/**
 * Model Zone
 * 
 */
export type Zone = Prisma.ZoneModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model ApiToken
 * 
 */
export type ApiToken = Prisma.ApiTokenModel
/**
 * Model DnsRecord
 * 
 */
export type DnsRecord = Prisma.DnsRecordModel
/**
 * Model UpdateLog
 * 
 */
export type UpdateLog = Prisma.UpdateLogModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
/**
 * Model NotificationChannel
 * 
 */
export type NotificationChannel = Prisma.NotificationChannelModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
