
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  CloudflareAccount: 'CloudflareAccount',
  Zone: 'Zone',
  User: 'User',
  ApiToken: 'ApiToken',
  DnsRecord: 'DnsRecord',
  UpdateLog: 'UpdateLog',
  Settings: 'Settings',
  NotificationChannel: 'NotificationChannel',
  AuditLog: 'AuditLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CloudflareAccountScalarFieldEnum = {
  id: 'id',
  providerType: 'providerType',
  label: 'label',
  email: 'email',
  apiToken: 'apiToken',
  createdAt: 'createdAt'
} as const

export type CloudflareAccountScalarFieldEnum = (typeof CloudflareAccountScalarFieldEnum)[keyof typeof CloudflareAccountScalarFieldEnum]


export const ZoneScalarFieldEnum = {
  id: 'id',
  cfZoneId: 'cfZoneId',
  name: 'name',
  accountId: 'accountId'
} as const

export type ZoneScalarFieldEnum = (typeof ZoneScalarFieldEnum)[keyof typeof ZoneScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  twoFactorSecret: 'twoFactorSecret',
  twoFactorEnabled: 'twoFactorEnabled',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ApiTokenScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tokenHash: 'tokenHash',
  userId: 'userId',
  lastUsedAt: 'lastUsedAt',
  createdAt: 'createdAt'
} as const

export type ApiTokenScalarFieldEnum = (typeof ApiTokenScalarFieldEnum)[keyof typeof ApiTokenScalarFieldEnum]


export const DnsRecordScalarFieldEnum = {
  id: 'id',
  cfRecordId: 'cfRecordId',
  name: 'name',
  type: 'type',
  content: 'content',
  isAutoUpdate: 'isAutoUpdate',
  proxied: 'proxied',
  updateToken: 'updateToken',
  zoneId: 'zoneId'
} as const

export type DnsRecordScalarFieldEnum = (typeof DnsRecordScalarFieldEnum)[keyof typeof DnsRecordScalarFieldEnum]


export const UpdateLogScalarFieldEnum = {
  id: 'id',
  oldIp: 'oldIp',
  newIp: 'newIp',
  status: 'status',
  recordId: 'recordId',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type UpdateLogScalarFieldEnum = (typeof UpdateLogScalarFieldEnum)[keyof typeof UpdateLogScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const NotificationChannelScalarFieldEnum = {
  id: 'id',
  type: 'type',
  label: 'label',
  config: 'config',
  enabled: 'enabled',
  createdAt: 'createdAt'
} as const

export type NotificationChannelScalarFieldEnum = (typeof NotificationChannelScalarFieldEnum)[keyof typeof NotificationChannelScalarFieldEnum]


export const AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  target: 'target',
  details: 'details',
  createdAt: 'createdAt'
} as const

export type AuditLogScalarFieldEnum = (typeof AuditLogScalarFieldEnum)[keyof typeof AuditLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

